{
  "hash": "79fb405316f19fe2141eca6dce976143",
  "result": {
    "engine": "knitr",
    "markdown": "# Advanced Biostatistical Methods in Drug Development\n\n## Introduction\n\nModern clinical drug development relies on sophisticated statistical methods that go beyond traditional fixed-sample, single-endpoint trial designs. This chapter covers advanced methods essential for efficient, rigorous development programs:\n\n- **Adaptive designs**: Flexible modification of trial characteristics based on accumulating data\n- **Multiple testing**: Controlling error rates when testing many hypotheses\n- **Estimand framework**: Clear specification of treatment effects for complex intercurrent events\n- **Missing data**: Principled approaches to incomplete data beyond simple deletion\n- **Meta-analysis**: Systematic synthesis of evidence across multiple studies\n- **Biomarker-driven designs**: Enrichment and precision medicine approaches\n\nThese methods, when properly implemented, improve efficiency, reduce development time, and provide stronger evidence for regulatory decision-making.\n\n---\n\n## 1. Adaptive Clinical Trial Designs\n\n### 1.1 Group Sequential Designs\n\nA **group sequential design** allows for interim analyses, with the possibility of stopping early for efficacy, futility, or both.\n\n#### 1.1.1 O'Brien-Fleming Boundary\n\nMore conservative early stopping for efficacy, allocates more Type I error to final analysis:\n\n- At interim analysis 1: p-value threshold ≈ 0.005 (more stringent)\n- At final analysis: p-value threshold ≈ 0.047 (less stringent)\n\nEnsures strong early efficacy evidence before stopping, reduces false positives.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# O'Brien-Fleming boundary for 2 interim analyses + 1 final\nif (requireNamespace(\"gsDesign\", quietly = TRUE)) {\n  design_of <- gsDesign::gsDesign(k = 3,  # 3 analyses total\n                                  test.type = 2,  # symmetric 2-sided (OF/Pocock require symmetric)\n                                  sfu = \"OF\",  # O'Brien-Fleming\n                                  alpha = 0.05,\n                                  beta = 0.20)\n\n  design_of$upper$bound  # Efficacy boundaries\n  design_of$lower$bound  # Futility boundaries\n} else {\n  message(\"gsDesign not available; install with install.packages('gsDesign')\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] -2.961125 -2.093831 -1.709606\n```\n\n\n:::\n:::\n\n\n\n\n#### 1.1.2 Pocock Boundary\n\nMore aggressive early stopping for efficacy, uniform p-value threshold across analyses:\n\n- At each analysis: p-value threshold ≈ 0.016 (for 3 analyses)\n\nHigher power to detect effect early, but slightly increased false positive risk.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Pocock boundary\nif (requireNamespace(\"gsDesign\", quietly = TRUE)) {\n  design_poc <- gsDesign::gsDesign(k = 3,\n                                  test.type = 2,  # symmetric 2-sided (Pocock requires symmetric)\n                                  sfu = \"Pocock\",\n                                  alpha = 0.05,\n                                  beta = 0.20)\n\n  design_poc$upper$bound\n} else {\n  message(\"gsDesign not available; install with install.packages('gsDesign')\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> [1] 1.992186 1.992186 1.992186\n```\n\n\n:::\n:::\n\n\n\n\n#### 1.1.3 Sample Size Inflation\n\nGroup sequential designs require **information inflation factor**: additional subjects beyond fixed-sample design to maintain power:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Information inflation factor\n# Fixed sample size for 80% power, 2-sided test\nif (requireNamespace(\"pwr\", quietly = TRUE) &&\n    requireNamespace(\"gsDesign\", quietly = TRUE)) {\n  n_fixed <- pwr::pwr.t.test(d = 0.5, sig.level = 0.05, power = 0.80)$n\n  n_fixed <- ceiling(n_fixed)\n\n  # With group sequential design (2 looks, O'Brien-Fleming)\n  design_gs <- gsDesign::gsDesign(k = 2, test.type = 2,\n                                 sfu = \"OF\", alpha = 0.05, beta = 0.20)\n  inflation_factor <- design_gs$n.I[2] / n_fixed\n\n  cat(\"Fixed sample size:\", n_fixed, \"\\n\")\n  cat(\"GSD sample size:\", design_gs$n.I[2], \"\\n\")\n  cat(\"Inflation factor:\", round(inflation_factor, 3), \"\\n\")\n} else {\n  message(\"pwr or gsDesign not available\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Fixed sample size: 64 \n#> GSD sample size: 1.015614 \n#> Inflation factor: 0.016\n```\n\n\n:::\n:::\n\n\n\n\n### 1.2 Adaptive Seamless Phase II/III Designs\n\nCombines phase II and phase III in a single trial structure:\n\n1. **Phase II component** (first stage): Identify promising dose(s)\n2. **Seamless transition**: Drop futile doses, continue promising dose(s)\n3. **Phase III component** (second stage): Confirmatory efficacy testing\n\nAdvantages:\n- Faster development timeline\n- Shared control group across phases\n- More efficient use of subjects\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Simplified example: two-stage adaptive dose selection\n# Phase II: Three doses (5, 10, 20 mg) vs. placebo\n# Phase III: Continue best-performing dose vs. placebo\n\n# Phase II (hypothetical results)\ndose_effects <- data.frame(\n  Dose = c(\"Placebo\", \"5mg\", \"10mg\", \"20mg\"),\n  Mean_Change = c(-2, -6, -9, -8),  # Blood pressure change\n  SE = c(1.5, 1.5, 1.5, 1.5),\n  N = c(40, 40, 40, 40)\n)\n\n# Select dose with largest effect (10 mg)\nbest_dose <- dose_effects[which.max(dose_effects$Mean_Change[2:4]) + 1, ]\ncat(\"Selected dose for Phase III:\", best_dose$Dose, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Selected dose for Phase III: 5mg\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Phase III: Compare selected dose to placebo with larger sample\n# n = 150 per group (increased from 40 in Phase II)\n```\n:::\n\n\n\n\n### 1.3 Sample Size Re-estimation\n\nAllows prospective increase in sample size based on interim analysis data:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Interim analysis at 50% information\n# Blinded review of variability estimate\n# If SD larger than anticipated, increase sample size\n\nsd_anticipated <- 10\nsd_observed_interim <- 12.5  # 25% larger\n\n# Reestimate required sample size\nn_original <- 100  # per group\nvariance_ratio <- (sd_observed_interim / sd_anticipated)^2\nn_updated <- ceiling(n_original * variance_ratio)\n\ncat(\"Original sample size per group:\", n_original, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Original sample size per group: 100\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Updated sample size per group:\", n_updated, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Updated sample size per group: 157\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Additional subjects needed:\", n_updated - n_original, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Additional subjects needed: 57\n```\n\n\n:::\n:::\n\n\n\n\n### 1.4 Response-Adaptive Randomization\n\nAllocates more subjects to treatments showing promise during the trial:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Bandit algorithm: allocate subjects based on observed response rates\n# Initially: 1:1 randomization\n# As data accumulate: shift allocation toward higher-response treatment\n\nset.seed(42)\nn_total <- 200\nresponse_rate_a <- 0.55\nresponse_rate_b <- 0.45\n\n# Track cumulative allocation\nallocation <- numeric(n_total)\nresponses_a <- 0\nresponses_b <- 0\n\nfor (i in 1:n_total) {\n  # Thompson sampling: sample from posterior distributions\n  # Allocate to treatment with highest posterior probability of response\n\n  posterior_a <- rbeta(1, responses_a + 1, (i/2 - responses_a) + 1)\n  posterior_b <- rbeta(1, responses_b + 1, (i/2 - responses_b) + 1)\n\n  if (isTRUE(posterior_a > posterior_b)) {\n    allocation[i] <- 1  # Assign to A\n    responses_a <- responses_a + rbinom(1, 1, response_rate_a)\n  } else {\n    allocation[i] <- 0  # Assign to B\n    responses_b <- responses_b + rbinom(1, 1, response_rate_b)\n  }\n}\n\n# Compare adaptive allocation to fixed 1:1\ncat(\"Fixed 1:1 allocation: 100 per arm\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Fixed 1:1 allocation: 100 per arm\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Adaptive allocation: \",\n    sum(allocation == 1), \"to A, \",\n    sum(allocation == 0), \"to B\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Adaptive allocation:  163 to A,  37 to B\n```\n\n\n:::\n:::\n\n\n\n\n---\n\n## 2. Multiple Testing in Clinical Trials\n\n### 2.1 Familywise Error Rate (FWER)\n\n**FWER** is the probability of making at least one Type I error across multiple tests:\n\n$$FWER = P(\\text{reject at least one } H_0 | \\text{all } H_0 \\text{ true})$$\n\nTraditional methods control FWER at α = 0.05.\n\n### 2.2 False Discovery Rate (FDR)\n\n**FDR** is the proportion of false positives among all rejected hypotheses:\n\n$$FDR = E\\left[\\frac{V}{R}\\right]$$\n\nwhere V = number of false positives, R = number of rejections.\n\nFDR control is less stringent than FWER, useful for exploratory analyses.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# FWER vs FDR control\n# m = 10 hypotheses, true effect size for 2 of them\n\nset.seed(42)\nm <- 10\ntrue_effects <- c(0.5, 0.5, rep(0, 8))  # True effects for first 2\n\n# Generate p-values\np_values <- numeric(m)\nfor (i in 1:m) {\n  if (true_effects[i] > 0) {\n    # Power = 0.80 for true effects\n    p_values[i] <- 1 - pnorm(abs(rnorm(1, mean = true_effects[i], sd = 1)))\n  } else {\n    p_values[i] <- runif(1)\n  }\n}\n\n# Bonferroni (FWER control): Reject if p < α/m\nbonferroni_threshold <- 0.05 / m\nbonferroni_reject <- p_values < bonferroni_threshold\n\n# FDR (Benjamini-Hochberg): Reject if p <= threshold(i)\nfdr_threshold <- 0.05\nsorted_p <- sort(p_values)\nsorted_i <- 1:m\nbh_threshold <- (sorted_i / m) * fdr_threshold\nbh_reject <- sum(sorted_p <= bh_threshold)\n\ncat(\"Bonferroni rejections:\", sum(bonferroni_reject), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Bonferroni rejections: 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Benjamini-Hochberg rejections:\", bh_reject, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Benjamini-Hochberg rejections: 0\n```\n\n\n:::\n:::\n\n\n\n\n### 2.3 Hierarchical Testing Procedures\n\n#### 2.3.1 Fixed Sequence Procedure\n\nTests hypotheses in a pre-specified order, stops at first non-rejection:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Primary efficacy → Key secondary 1 → Key secondary 2\n# H1: Primary endpoint (strong control of Type I error)\n# H2: Key secondary 1 (only if H1 rejected)\n# H3: Key secondary 2 (only if H2 rejected)\n\np_values_seq <- c(0.008, 0.025, 0.032)  # Primary, Key Sec 1, Key Sec 2\nalpha_level <- 0.05\n\nrejections_fixed <- numeric(3)\nfor (i in 1:3) {\n  if (i == 1 || rejections_fixed[i-1] == 1) {\n    rejections_fixed[i] <- as.numeric(p_values_seq[i] < alpha_level)\n  } else {\n    break\n  }\n}\n\ncat(\"Fixed sequence rejections:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Fixed sequence rejections:\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfor (i in 1:3) {\n  cat(\"H\", i, \": \", ifelse(rejections_fixed[i] == 1, \"Rejected\", \"Not rejected\"), \"\\n\", sep=\"\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> H1: Rejected\n#> H2: Rejected\n#> H3: Rejected\n```\n\n\n:::\n:::\n\n\n\n\n#### 2.3.2 Fallback Procedure\n\nMore flexible: can test later hypotheses even if earlier ones fail, but with adjusted α:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fallback procedure\n# If H1 rejected: H2 tested at α = 0.05\n# If H1 not rejected: H2 tested at α = 0.025 (reduced)\n# If H2 rejected: H3 tested at remaining α\n\np_values_fb <- c(0.08, 0.02)  # Primary fails, secondary succeeds\nalpha_h1 <- 0.05\nalpha_h2_if_h1_rej <- 0.05\nalpha_h2_if_h1_not_rej <- 0.025\n\nh1_rejected <- p_values_fb[1] < alpha_h1\nh2_threshold <- ifelse(h1_rejected, alpha_h2_if_h1_rej, alpha_h2_if_h1_not_rej)\nh2_rejected <- p_values_fb[2] < h2_threshold\n\ncat(\"H1 (Primary):\", ifelse(h1_rejected, \"Rejected\", \"Not rejected\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> H1 (Primary): Not rejected\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"H2 threshold: alpha =\", h2_threshold, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> H2 threshold: alpha = 0.025\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"H2 (Secondary):\", ifelse(h2_rejected, \"Rejected\", \"Not rejected\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> H2 (Secondary): Rejected\n```\n\n\n:::\n:::\n\n\n\n\n### 2.4 Gatekeeping Procedures for Complex Hierarchies\n\nManages hierarchical families of hypotheses with conditional testing based on parent hypothesis results:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Hierarchical structure:\n# Primary: PK endpoint (Pharmacokinetics)\n#   └─ Secondary 1a: Efficacy measure 1\n#   └─ Secondary 1b: Efficacy measure 2\n# Safety: Adverse events\n#   └─ Secondary 2a: Specific AE rate\n#   └─ Secondary 2b: Lab abnormality rate\n\np_values_gate <- list(\n  Primary = 0.015,\n  Secondary_1a = 0.032,\n  Secondary_1b = 0.048,\n  Safety = 0.001,\n  Secondary_2a = 0.087,\n  Secondary_2b = 0.034\n)\n\n# Primary family (PK) has alpha = 0.04 (before safety)\n# Safety family has alpha = 0.01\n\nalpha_pk <- 0.04\nalpha_safety <- 0.01\n\n# Primary hypothesis\npk_rejected <- p_values_gate$Primary < alpha_pk\n\n# Secondary hypotheses in efficacy (gated by PK)\nif (pk_rejected) {\n  sec1a_rejected <- p_values_gate$Secondary_1a < alpha_pk/2\n  sec1b_rejected <- p_values_gate$Secondary_1b < alpha_pk/2\n} else {\n  sec1a_rejected <- sec1b_rejected <- FALSE\n}\n\n# Safety hypotheses (separate gating)\nsafety_rejected <- p_values_gate$Safety < alpha_safety\nif (safety_rejected) {\n  sec2a_rejected <- p_values_gate$Secondary_2a < alpha_safety/2\n  sec2b_rejected <- p_values_gate$Secondary_2b < alpha_safety/2\n} else {\n  sec2a_rejected <- sec2b_rejected <- FALSE\n}\n\ncat(\"PK Endpoint:\", ifelse(pk_rejected, \"Positive\", \"Negative\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> PK Endpoint: Positive\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"├─ Efficacy Measure 1:\", ifelse(sec1a_rejected, \"Positive\", \"Negative\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ├─ Efficacy Measure 1: Negative\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"├─ Efficacy Measure 2:\", ifelse(sec1b_rejected, \"Positive\", \"Negative\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ├─ Efficacy Measure 2: Negative\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Safety Endpoint:\", ifelse(safety_rejected, \"Positive\", \"Negative\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Safety Endpoint: Positive\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"├─ Specific AE:\", ifelse(sec2a_rejected, \"Positive\", \"Negative\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> ├─ Specific AE: Negative\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"└─ Lab Abnormality:\", ifelse(sec2b_rejected, \"Positive\", \"Negative\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> └─ Lab Abnormality: Negative\n```\n\n\n:::\n:::\n\n\n\n\n### 2.5 Multiplicity Adjustment Methods\n\n#### 2.5.1 Bonferroni\n\nDivides α equally among m tests:\n\n$$p\\text{-value threshold} = \\frac{\\alpha}{m}$$\n\nConservative (FWER control), but powerful when few tests.\n\n#### 2.5.2 Holm's Procedure\n\nMore powerful than Bonferroni; rejects ordered hypotheses at thresholds:\n- H₁: p < α/m\n- H₂: p < α/(m-1)\n- H₃: p < α/(m-2), etc.\n\nMaintains FWER control while improving power.\n\n#### 2.5.3 Hochberg and Hommel\n\nEven more powerful methods; use step-up approach:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Example: 5 hypotheses with p-values\np_values_mult <- c(0.001, 0.008, 0.035, 0.042, 0.105)\nalpha <- 0.05\nm <- length(p_values_mult)\n\n# Bonferroni\nbonferroni_sig <- p_values_mult < alpha / m\n\n# Holm\nsorted_p <- sort(p_values_mult)\nholm_threshold <- alpha / (m:1)\nholm_sig <- sorted_p < holm_threshold\n\n# Benjamini-Hochberg (FDR)\nsorted_i <- 1:m\nbh_threshold <- (sorted_i / m) * alpha\nbh_sig <- sorted_p < bh_threshold\n\nresults_table <- data.frame(\n  Test = 1:m,\n  P_value = p_values_mult,\n  Bonferroni = bonferroni_sig,\n  Holm = cumsum(holm_sig) > 0,\n  BH_FDR = cumsum(bh_sig) > 0\n)\nprint(results_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   Test P_value Bonferroni Holm BH_FDR\n#> 1    1   0.001       TRUE TRUE   TRUE\n#> 2    2   0.008       TRUE TRUE   TRUE\n#> 3    3   0.035      FALSE TRUE   TRUE\n#> 4    4   0.042      FALSE TRUE   TRUE\n#> 5    5   0.105      FALSE TRUE   TRUE\n```\n\n\n:::\n:::\n\n\n\n\n---\n\n## 3. Estimand Framework (ICH E9(R1))\n\n### 3.1 Definition and Components\n\nAn **estimand** specifies:\n1. **Population**: Target population\n2. **Variable**: What is measured (primary outcome)\n3. **Intercurrent events**: Events that occur during trial (drop-out, medication switches, disease progression)\n4. **Population-level summary**: How individual observations are combined (mean difference, probability difference)\n\n### 3.2 Handling Intercurrent Events\n\nFive strategies for handling intercurrent events:\n\n#### 3.2.1 Treatment Policy Strategy\nIgnores intercurrent event, analyzes all subjects as randomized (intention-to-treat).\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Analyze all randomized subjects regardless of adherence/dropout\n# This is the standard ITT approach\n```\n:::\n\n\n\n\n#### 3.2.2 Composite Strategy\nDefines intercurrent event as part of outcome (e.g., failure if subject stops treatment).\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Failure = either lack of efficacy OR treatment discontinuation\n# More conservative, clinically relevant approach\n```\n:::\n\n\n\n\n#### 3.2.3 Hypothetical Strategy\nEstimates what would have happened if intercurrent event had not occurred.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Estimate efficacy adjusting for non-adherence\n# More ambitious, requires strong assumptions (MCAR)\n```\n:::\n\n\n\n\n#### 3.2.4 While-on-Treatment Strategy\nAnalyzes only the period while subject is on treatment.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Exclude post-discontinuation data\n# Can introduce bias if discontinuation related to outcome\n```\n:::\n\n\n\n\n#### 3.2.5 Principal Stratum Strategy\nConditions on whether subject would experience intercurrent event.\n\n---\n\n## 4. Missing Data Methods\n\n### 4.1 Missing Data Mechanisms\n\n- **MCAR (Missing Completely at Random)**: Missingness unrelated to observed or unobserved outcomes\n- **MAR (Missing at Random)**: Missingness depends on observed data but not unobserved outcomes\n- **MNAR (Missing Not at Random)**: Missingness depends on unobserved outcomes\n\nOnly MCAR justifies listwise deletion. MAR and MNAR require more sophisticated methods.\n\n### 4.2 Multiple Imputation (MICE Framework)\n\nMultiple Imputation by Chained Equations:\n\n1. **Imputation**: Create m complete datasets by imputing missing values\n2. **Analysis**: Analyze each complete dataset separately\n3. **Pooling**: Combine results using Rubin's rules\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nif (requireNamespace(\"mice\", quietly = TRUE)) {\n  # Create example dataset with missing values\n  set.seed(42)\n  trial_data_incomplete <- data.frame(\n    subject_id = 1:100,\n    treatment = rep(c(\"Active\", \"Control\"), 50),\n    age = rnorm(100, 55, 10),\n    baseline_outcome = rnorm(100, 50, 10),\n    final_outcome = rnorm(100, 55, 12)\n  )\n\n  # Introduce missing data (MCAR for simplicity)\n  missing_idx <- sample(1:100, 20)\n  trial_data_incomplete$final_outcome[missing_idx] <- NA\n\n  # Multiple imputation (m = 5 imputations)\n  imputed_data <- mice::mice(trial_data_incomplete,\n                             m = 5, maxit = 50,\n                             method = \"norm\", print = FALSE)\n\n  # Analyze and pool: use base-R with() for S3 dispatch on mids objects\n  fits_mids <- with(imputed_data,\n                    lm(final_outcome ~ treatment + baseline_outcome))\n  pooled_results <- mice::pool(fits_mids)\n  print(summary(pooled_results))\n} else {\n  message(\"mice not available; install with install.packages('mice')\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>               term    estimate std.error statistic       df      p.value\n#> 1      (Intercept) 52.59167434 8.1171668 6.4790678 39.79331 1.026124e-07\n#> 2 treatmentControl  1.28934252 2.7391408 0.4707106 66.75744 6.393819e-01\n#> 3 baseline_outcome  0.03432461 0.1590727 0.2157794 46.20113 8.301096e-01\n```\n\n\n:::\n:::\n\n\n\n\n**Advantages**:\n- Handles MAR data properly\n- Preserves uncertainty from missingness\n- Flexible for different imputation models\n\n**Disadvantages**:\n- Assumes MAR (not testable)\n- Requires specification of imputation model\n\n### 4.3 Pattern Mixture Models\n\nExplicitly model the relationship between missingness and outcome:\n\n$$E[Y | X, \\text{dropout}] = \\alpha_{\\text{dropout}} + \\beta X$$\n\nCoefficients can differ between subjects who drop out vs. complete follow-up.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Pattern mixture model: complete vs. dropout patterns\n# Create a self-contained dataset for this demonstration\nset.seed(42)\ntrial_data_pmm <- data.frame(\n  subject_id       = 1:100,\n  treatment        = rep(c(\"Active\", \"Control\"), 50),\n  baseline_outcome = rnorm(100, 50, 10),\n  final_outcome    = rnorm(100, 55, 12)\n)\n# Introduce missingness\nmissing_idx2 <- sample(1:100, 20)\ntrial_data_pmm$final_outcome[missing_idx2] <- NA\ntrial_data_pmm$pattern <- ifelse(is.na(trial_data_pmm$final_outcome),\n                                  \"Dropout\", \"Complete\")\n\ncomplete_data <- subset(trial_data_pmm, pattern == \"Complete\")\ndropout_data  <- subset(trial_data_pmm, pattern == \"Dropout\")\n\ncat(\"Complete follow-up:\", nrow(complete_data), \"subjects\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Complete follow-up: 80 subjects\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Early dropout:     \", nrow(dropout_data),  \"subjects\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Early dropout:      20 subjects\n```\n\n\n:::\n\n```{.r .cell-code}\n# Analyze observed data in completers\nfit_complete <- lm(final_outcome ~ treatment + baseline_outcome,\n                   data = complete_data)\ncat(\"\nPattern mixture model (completers):\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Pattern mixture model (completers):\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(coef(summary(fit_complete)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                     Estimate Std. Error   t value     Pr(>|t|)\n#> (Intercept)      54.12081969  6.8287148  7.925477 1.415213e-11\n#> treatmentControl  2.92517008  2.5542715  1.145207 2.556704e-01\n#> baseline_outcome -0.02937634  0.1303258 -0.225407 8.222599e-01\n```\n\n\n:::\n:::\n\n\n\n\n### 4.4 Sensitivity and Tipping Point Analysis\n\n**Sensitivity analysis** explores robustness to different assumptions about missingness:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Tipping point analysis: at what assumed outcome for Active dropouts\n# does the treatment conclusion flip to zero?\n# Key: vary Active dropout assumption; keep Control dropout = observed mean (50)\n\nn_completers <- 80; n_missing <- 20; n_total <- 100\nobs_active <- 55; obs_control <- 50\n\n# Range must cross the tipping point: when Active imputed = 30, effect = 0\n# (55*80 + 30*20)/100 - 50 = 50 - 50 = 0\nmissing_outcome_active <- seq(28, 57, by = 1)\n\ntreatment_effect <- sapply(missing_outcome_active, function(x) {\n  mean_active  <- (obs_active  * n_completers + x  * n_missing) / n_total\n  mean_control <- (obs_control * n_completers + obs_control * n_missing) / n_total\n  mean_active - mean_control\n})\n\n# Find tipping point (treatment effect = 0) via linear interpolation\ntipping_point_result <- tryCatch(\n  approx(treatment_effect, missing_outcome_active, xout = 0)$y,\n  error = function(e) NA\n)\n\ncat(\"Observed treatment effect:\", obs_active - obs_control, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Observed treatment effect: 5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nif (!is.na(tipping_point_result)) {\n  cat(\"Tipping point (Active dropout mean that nullifies effect):\",\n      round(tipping_point_result, 2), \"\\n\")\n  cat(\"(Effect flips sign if Active dropouts score below ~\",\n      round(tipping_point_result, 1), \"on average)\\n\")\n} else {\n  cat(\"Tipping point: treatment effect does not cross zero in specified range\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Tipping point (Active dropout mean that nullifies effect): 30 \n#> (Effect flips sign if Active dropouts score below ~ 30 on average)\n```\n\n\n:::\n:::\n\n\n\n\n---\n\n## 5. Meta-Analysis\n\n### 5.1 Fixed-Effects Model\n\nAssumes all studies estimate the same true effect:\n\n$$\\theta_i = \\theta + \\epsilon_i$$\n\nwhere $\\epsilon_i$ is within-study variability.\n\nPooled estimate (inverse variance weighting):\n\n$$\\hat{\\theta} = \\frac{\\sum w_i \\hat{\\theta}_i}{\\sum w_i}$$\n\nwhere $w_i = 1 / SE_i^2$ (inverse variance weight).\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nif (!requireNamespace(\"meta\", quietly = TRUE)) {\n  message(\"meta package not available; skipping meta-analysis examples.\")\n} else {\n\n# Meta-analysis of antihypertensive drug efficacy\n# 5 studies comparing drug to placebo\n\nstudies <- data.frame(\n  Study = c(\"Study A\", \"Study B\", \"Study C\", \"Study D\", \"Study E\"),\n  Mean_Diff = c(-10, -12, -8, -11, -9),  # mmHg reduction\n  SE = c(2.0, 2.2, 1.8, 2.1, 1.9)\n)\n\n# Meta-analysis (fixed-effects)\nmeta_fe <- meta::metagen(TE = Mean_Diff,\n                        seTE = SE,\n                        studlab = Study,\n                        data = studies,\n                        fixed = TRUE,\n                        random = FALSE)\n\nsummary(meta_fe)\n} # end requireNamespace(\"meta\") guard\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                               95%-CI %W(common)\n#> Study A -10.0000 [-13.9199; -6.0801]       19.7\n#> Study B -12.0000 [-16.3119; -7.6881]       16.3\n#> Study C  -8.0000 [-11.5279; -4.4721]       24.3\n#> Study D -11.0000 [-15.1159; -6.8841]       17.9\n#> Study E  -9.0000 [-12.7239; -5.2761]       21.8\n#> \n#> Number of studies: k = 5\n#> \n#>                                          95%-CI      z  p-value\n#> Common effect model -9.7996 [-11.5395; -8.0597] -11.04 < 0.0001\n#> \n#> Quantifying heterogeneity (with 95%-CIs):\n#>  tau^2 = 0 [0.0000; 16.6202]; tau = 0 [0.0000; 4.0768]\n#>  I^2 = 0.0% [0.0%; 79.2%]; H = 1.00 [1.00; 2.19]\n#> \n#> Test of heterogeneity:\n#>     Q d.f. p-value\n#>  2.51    4  0.6422\n#> \n#> Details of meta-analysis methods:\n#> - Inverse variance method\n#> - Restricted maximum-likelihood estimator for tau^2\n#> - Q-Profile method for confidence interval of tau^2 and tau\n#> - Calculation of I^2 based on Q\n```\n\n\n:::\n:::\n\n\n\n\n### 5.2 Random-Effects Model\n\nAssumes studies estimate different true effects, drawn from distribution:\n\n$$\\theta_i = \\mu + \\eta_i + \\epsilon_i$$\n\nwhere:\n- μ = mean effect across studies\n- η_i = between-study heterogeneity\n- ε_i = within-study error\n\nDerSimonian-Laird estimator for between-study variance:\n\n$$\\hat{\\tau}^2 = \\frac{Q - (k-1)}{\\sum w_i - \\frac{\\sum w_i^2}{\\sum w_i}}$$\n\nwhere Q = heterogeneity statistic.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nif (requireNamespace(\"meta\", quietly = TRUE) && exists(\"studies\")) {\n  # Meta-analysis (random-effects)\n  meta_re <- meta::metagen(TE = Mean_Diff,\n                           seTE = SE,\n                           studlab = Study,\n                           data = studies,\n                           fixed = FALSE,\n                           random = TRUE,\n                           method.tau = \"DL\")  # DerSimonian-Laird\n  summary(meta_re)\n} else {\n  message(\"meta package not available or studies dataset not found\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                               95%-CI %W(random)\n#> Study A -10.0000 [-13.9199; -6.0801]       19.7\n#> Study B -12.0000 [-16.3119; -7.6881]       16.3\n#> Study C  -8.0000 [-11.5279; -4.4721]       24.3\n#> Study D -11.0000 [-15.1159; -6.8841]       17.9\n#> Study E  -9.0000 [-12.7239; -5.2761]       21.8\n#> \n#> Number of studies: k = 5\n#> \n#>                                           95%-CI      z  p-value\n#> Random effects model -9.7996 [-11.5395; -8.0597] -11.04 < 0.0001\n#> \n#> Quantifying heterogeneity (with 95%-CIs):\n#>  tau^2 = 0 [0.0000; 16.6617]; tau = 0 [0.0000; 4.0819]\n#>  I^2 = 0.0% [0.0%; 79.2%]; H = 1.00 [1.00; 2.19]\n#> \n#> Test of heterogeneity:\n#>     Q d.f. p-value\n#>  2.51    4  0.6422\n#> \n#> Details of meta-analysis methods:\n#> - Inverse variance method\n#> - DerSimonian-Laird estimator for tau^2\n#> - Jackson method for confidence interval of tau^2 and tau\n#> - Calculation of I^2 based on Q\n```\n\n\n:::\n:::\n\n\n\n\n### 5.3 Heterogeneity Assessment\n\n#### 5.3.1 I² Statistic\n\nProportion of total variance due to heterogeneity:\n\n$$I^2 = \\frac{Q - (k-1)}{Q} \\times 100\\%$$\n\n- I² < 25%: Low heterogeneity\n- 25% < I² < 75%: Moderate heterogeneity\n- I² > 75%: High heterogeneity\n\n#### 5.3.2 τ² (Tau-Squared)\n\nBetween-study variance in original scale:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Extract heterogeneity measures\nif (requireNamespace(\"meta\", quietly = TRUE) && exists(\"meta_re\")) {\n  # Note: requires meta_re object from previous random-effects meta-analysis chunk\n  i2_value <- tryCatch(meta_re$I2$TE, error = function(e) NA)\n  tau2_value <- tryCatch(meta_re$tau2, error = function(e) NA)\n  tau_value <- tryCatch(meta_re$tau, error = function(e) NA)\n\n  if (!is.na(i2_value)) {\n    cat(\"I²:\", round(i2_value, 1), \"%\\n\")\n  }\n  if (!is.na(tau2_value)) {\n    cat(\"τ²:\", round(tau2_value, 2), \"\\n\")\n  }\n  if (!is.na(tau_value)) {\n    cat(\"τ:\", round(tau_value, 2), \"\\n\")\n  }\n  if (is.na(i2_value) && is.na(tau2_value) && is.na(tau_value)) {\n    message(\"Could not extract heterogeneity measures from meta_re object\")\n  }\n} else {\n  message(\"meta package not available or meta_re object not found\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> τ²: 0 \n#> τ: 0\n```\n\n\n:::\n:::\n\n\n\n\n### 5.4 Forest Plots\n\nGraphical representation of individual studies and pooled estimate:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Forest plot\nif (requireNamespace(\"meta\", quietly = TRUE) && exists(\"meta_re\")) {\n  plot(meta_re, xlim = c(-20, 0))\n} else {\n  message(\"meta package or meta_re object not found; run random-effects meta-analysis chunk first\")\n}\n```\n\n::: {.cell-output-display}\n![](bs08-advanced-biostatistics_files/figure-html/unnamed-chunk-35-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\n### 5.5 Publication Bias\n\n#### 5.5.1 Funnel Plot\n\nScatterplot of effect size vs. study precision; asymmetry suggests publication bias:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Funnel plot\nif (requireNamespace(\"metafor\", quietly = TRUE) && requireNamespace(\"meta\", quietly = TRUE) && exists(\"meta_re\")) {\n  tryCatch(\n    metafor::funnel(meta_re, main = \"Funnel Plot\"),\n    error = function(e) message(\"Could not create funnel plot: \", e$message)\n  )\n} else {\n  message(\"metafor/meta package or meta_re object not found\")\n}\n```\n\n::: {.cell-output-display}\n![](bs08-advanced-biostatistics_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\n#### 5.5.2 Egger's Test\n\nTests for asymmetry in funnel plot:\n\n$$z_i = \\frac{\\hat{\\theta}_i}{SE_i} = \\alpha + \\beta \\frac{1}{SE_i}$$\n\nSignificant intercept (α) suggests publication bias.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Egger's test for publication bias\nif (requireNamespace(\"meta\", quietly = TRUE) && exists(\"meta_re\")) {\n  tryCatch(\n    {\n      egger_result <- meta::metabias(meta_re, method = \"Egger\")\n      print(egger_result)\n    },\n    error = function(e) message(\"Could not compute Egger's test: \", e$message)\n  )\n} else {\n  message(\"meta package or meta_re object not found\")\n}\n```\n:::\n\n\n\n\n---\n\n## 6. Biomarker Analysis and Enrichment\n\n### 6.1 Predictive vs. Prognostic Biomarkers\n\n- **Predictive**: Modifies treatment response (predicts who benefits)\n- **Prognostic**: Associated with outcome regardless of treatment\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Analyze biomarker as predictor of treatment response\nset.seed(42)\nbiomarker_trial <- data.frame(\n  subject_id = 1:200,\n  treatment = rep(c(\"Active\", \"Control\"), 100),\n  biomarker = rnorm(200, 0, 1),\n  response = rbinom(200, 1, 0.5)\n)\n\n# Logistic regression: test biomarker × treatment interaction (predictive)\nfit_predictive <- glm(response ~ treatment + biomarker + treatment:biomarker,\n                     family = binomial,\n                     data = biomarker_trial)\nsummary(fit_predictive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> glm(formula = response ~ treatment + biomarker + treatment:biomarker, \n#>     family = binomial, data = biomarker_trial)\n#> \n#> Coefficients:\n#>                            Estimate Std. Error z value Pr(>|z|)\n#> (Intercept)                -0.03703    0.20047  -0.185    0.853\n#> treatmentControl           -0.36936    0.28624  -1.290    0.197\n#> biomarker                   0.05083    0.20965   0.242    0.808\n#> treatmentControl:biomarker  0.02852    0.29470   0.097    0.923\n#> \n#> (Dispersion parameter for binomial family taken to be 1)\n#> \n#>     Null deviance: 274.83  on 199  degrees of freedom\n#> Residual deviance: 272.99  on 196  degrees of freedom\n#> AIC: 280.99\n#> \n#> Number of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# If treatment:biomarker significant, biomarker is predictive\n# If only biomarker significant (no interaction), biomarker is prognostic\n```\n:::\n\n\n\n\n### 6.2 Biomarker-Stratified Design\n\nEnrolls only patients with specific biomarker status:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Enrichment design: enroll only biomarker-positive patients\nenriched_trial <- biomarker_trial[biomarker_trial$biomarker > 0, ]\n\n# Compare treatment effect in enriched population\nfit_enriched <- glm(response ~ treatment,\n                   family = binomial,\n                   data = enriched_trial)\nsummary(fit_enriched)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Call:\n#> glm(formula = response ~ treatment, family = binomial, data = enriched_trial)\n#> \n#> Coefficients:\n#>                  Estimate Std. Error z value Pr(>|z|)\n#> (Intercept)       0.08338    0.28893   0.289    0.773\n#> treatmentControl -0.28818    0.40739  -0.707    0.479\n#> \n#> (Dispersion parameter for binomial family taken to be 1)\n#> \n#>     Null deviance: 134.38  on 96  degrees of freedom\n#> Residual deviance: 133.88  on 95  degrees of freedom\n#> AIC: 137.88\n#> \n#> Number of Fisher Scoring iterations: 3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Typically larger treatment effect in enriched population\n```\n:::\n\n\n\n\n### 6.3 Adaptive Biomarker Thresholding\n\nOptimize biomarker threshold using interim data:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Interim analysis: optimize biomarker cutoff\ninterim_data <- biomarker_trial[1:100, ]\n\n# Test different cutoffs\ncutoffs <- seq(-2, 2, by = 0.5)\ntreatment_effects <- numeric(length(cutoffs))\n\nfor (i in seq_along(cutoffs)) {\n  stratified_data <- interim_data[interim_data$biomarker > cutoffs[i], ]\n  if (nrow(stratified_data) > 10) {\n    fit_temp <- glm(response ~ treatment,\n                   family = binomial,\n                   data = stratified_data)\n    treatment_effects[i] <- coef(fit_temp)[\"treatmentControl\"]\n  } else {\n    treatment_effects[i] <- NA\n  }\n}\n\n# Select cutoff with largest treatment effect\noptimal_cutoff <- cutoffs[which.max(abs(treatment_effects))]\ncat(\"Optimal biomarker cutoff:\", round(optimal_cutoff, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Optimal biomarker cutoff: -0.5\n```\n\n\n:::\n:::\n\n\n\n\n---\n\n## 7. R Implementations\n\n### 7.1 Adaptive Designs\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# gsDesign: group sequential designs\nif (requireNamespace(\"gsDesign\", quietly = TRUE)) {\n  design <- gsDesign::gsDesign(k = 2, test.type = 2, sfu = \"OF\",\n                    alpha = 0.05, beta = 0.20)\n\n  # Sequential spending function (test.type = 2 required for Pocock/OF boundaries)\n  gsDesign::gsDesign(k = 4, test.type = 2, sfu = \"Pocock\",\n          alpha = 0.05, beta = 0.20)\n} else {\n  message(\"gsDesign not available; install with install.packages('gsDesign')\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Symmetric two-sided group sequential design with\n#> 80 % power and 5 % Type I Error.\n#> Spending computations assume trial stops\n#> if a bound is crossed.\n#> \n#>            Sample\n#>             Size \n#>   Analysis Ratio*  Z   Nominal p  Spend\n#>          1  0.306 2.07    0.0193 0.0193\n#>          2  0.612 2.07    0.0193 0.0132\n#>          3  0.918 2.07    0.0193 0.0098\n#>          4  1.224 2.07    0.0193 0.0077\n#>      Total                       0.0500 \n#> \n#> ++ alpha spending:\n#>  Pocock boundary.\n#> * Sample size ratio compared to fixed design with no interim\n#> \n#> Boundary crossing probabilities and expected sample size\n#> assume any cross stops the trial\n#> \n#> Upper boundary (power or Type I Error)\n#>           Analysis\n#>    Theta      1      2      3      4 Total   E{N}\n#>   0.0000 0.0193 0.0132 0.0098 0.0077  0.05 1.1665\n#>   2.4865 0.2445 0.2455 0.1845 0.1255  0.80 0.7926\n#> \n#> Lower boundary (futility or Type II Error)\n#>           Analysis\n#>    Theta      1      2      3      4 Total\n#>   0.0000 0.0193 0.0132 0.0098 0.0077 5e-02\n#>   2.4865 0.0003 0.0000 0.0000 0.0000 3e-04\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# rpact: adaptive designs (guard — may not be installed)\nif (requireNamespace(\"rpact\", quietly = TRUE)) {\n  design_rpact <- rpact::getDesignGroupSequential(kMax = 3,\n                                                  typeOfDesign = \"OF\",\n                                                  alpha = 0.05,\n                                                  beta = 0.20)\n  print(design_rpact)\n} else {\n  message(\"rpact not available; install with install.packages('rpact')\")\n}\n```\n\n::: {.cell-output-display}\n*Design parameters and output of group sequential design*\n\n*User defined parameters*\n\n* *Significance level*: 0.0500 \n\n*Default parameters*\n\n* *Type of design*: O'Brien & Fleming \n* *Maximum number of stages*: 3 \n* *Stages*: 1, 2, 3 \n* *Information rates*: 0.333, 0.667, 1.000 \n* *Type II error rate*: 0.2000 \n* *Futility bounds (non-binding)*: -Inf, -Inf \n* *Binding futility*: FALSE \n* *Test*: one-sided \n* *Tolerance*: 1e-08 \n\n*Output*\n\n* *Cumulative alpha spending*: 0.001533, 0.018739, 0.050000 \n* *Critical values*: 2.961, 2.094, 1.710 \n* *Stage levels (one-sided)*: 0.001533, 0.018138, 0.043669 \n\n:::\n:::\n\n\n\n\n### 7.2 Multiple Testing\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Multiplicity adjustment (example with p_values from earlier sections)\np.adjust(p_values, method = \"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>  [1] 0.3067542 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000\n#>  [8] 1.0000000 1.0000000 1.0000000\n```\n\n\n:::\n\n```{.r .cell-code}\np.adjust(p_values, method = \"holm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>  [1] 0.3067542 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000\n#>  [8] 1.0000000 1.0000000 1.0000000\n```\n\n\n:::\n\n```{.r .cell-code}\np.adjust(p_values, method = \"BH\")  # Benjamini-Hochberg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>  [1] 0.3067542 0.7365883 0.7365883 0.7365883 0.7365883 0.6733330 0.7365883\n#>  [8] 0.7365883 0.7365883 0.7365883\n```\n\n\n:::\n\n```{.r .cell-code}\n# Hierarchical testing\n# Manual implementation or use gatekeeping() functions\n```\n:::\n\n\n\n\n### 7.3 Missing Data\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Reference: multiple imputation workflow (requires mice, Hmisc, missRanger)\nrequire(mice)\nimputed <- mice(data_with_missing, m = 5)\nfits <- with(imputed, lm(outcome ~ predictor))\npooled <- pool(fits)\n\nrequire(Hmisc)\nHmisc::aregImpute()  # Imputation by additive regression, bootstrapping\n\nrequire(missRanger)\nmissRanger::missRanger()  # Random forest imputation\n```\n:::\n\n\n\n\n### 7.4 Meta-Analysis\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Reference: meta-analysis workflow (requires meta, metafor, netmeta)\nrequire(meta)\nresult <- metagen(TE = effect, seTE = se_effect,\n                 studlab = study_name,\n                 fixed = FALSE, random = TRUE)\n\nrequire(metafor)  # Meta-regression, subgroup analyses\nrequire(netmeta)  # Network meta-analysis\n```\n:::\n\n\n\n\n### 7.5 Biomarker Analysis\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Reference: biomarker analysis (requires pROC)\n# Biomarker × treatment interaction\nglm(response ~ treatment + biomarker + treatment:biomarker,\n   family = binomial)\n\n# ROC curves for biomarker threshold optimization\nrequire(pROC)\nroc_obj <- roc(disease, biomarker_level)\n```\n:::\n\n\n\n\n---\n\n## 8. Exercises\n\n1. **Adaptive Designs**:\n   - Design group sequential trial with O'Brien-Fleming boundary\n   - Calculate sample size inflation factor\n   - Determine interim stopping thresholds\n\n2. **Multiple Testing**:\n   - Apply Bonferroni, Holm, and BH corrections to multiple p-values\n   - Compare number of rejections across methods\n   - Design hierarchical testing procedure for complex endpoint hierarchy\n\n3. **Estimands**:\n   - Specify estimand for trial with anticipated dropouts\n   - Choose appropriate intercurrent event strategy\n   - Plan sensitivity analyses\n\n4. **Missing Data**:\n   - Implement multiple imputation for MAR data\n   - Conduct tipping point analysis\n   - Compare treatment effect under different missingness assumptions\n\n5. **Meta-Analysis**:\n   - Pool results from multiple studies using fixed-effects model\n   - Compare to random-effects model\n   - Assess publication bias with funnel plot and Egger's test\n   - Interpret heterogeneity statistics\n\n6. **Biomarker Analysis**:\n   - Test for biomarker × treatment interaction (predictive)\n   - Evaluate biomarker-stratified design\n   - Optimize biomarker cutoff using interim data\n\n7. **Integration**:\n   - Design adaptive enrichment trial\n   - Specify multiple testing strategy for hierarchical endpoints\n   - Plan missing data handling approach\n   - Conduct sensitivity analyses\n\n---\n\n## Summary\n\nAdvanced biostatistical methods enhance clinical trial efficiency and rigor:\n\n- **Adaptive designs**: Early stopping, seamless phase designs, sample size re-estimation\n- **Multiple testing**: FWER vs FDR control, hierarchical and gatekeeping procedures\n- **Estimands**: Clear specification of treatment effects with intercurrent event handling\n- **Missing data**: Multiple imputation, pattern mixture models, sensitivity analyses\n- **Meta-analysis**: Fixed and random-effects models, heterogeneity assessment, publication bias\n- **Biomarker designs**: Predictive biomarker identification, enrichment strategies\n\nWhen properly integrated, these methods accelerate drug development while maintaining scientific rigor and regulatory acceptability.\n\n---\n\n## References and Further Reading\n\n- ICH E9(R1). (2019). Addendum on estimands and sensitivity analyses in clinical trials.\n- Peto, R. (1978). The design and analysis of long-term animal experiments. *Journal of the Royal Statistical Society*, 142, 151–183.\n- DerSimonian, R., & Laird, N. (1986). Meta-analysis in clinical trials. *Controlled Clinical Trials*, 7(3), 177–188.\n- Higgins, J.P.T., & Green, S. (Eds.). (2011). *Cochrane Handbook for Systematic Reviews of Interventions*. Wiley-Blackwell.\n- Little, R.J.A., & Rubin, D.B. (2002). *Statistical Analysis with Missing Data* (2nd ed.). Wiley.\n- Pocock, S.J., & Simon, R. (1975). Sequential treatment assignment with balancing for prognostic factors in the controlled clinical trial. *Biometrika*, 62(2), 375–386.\n- Jennison, C., & Turnbull, B.W. (2000). *Group Sequential Methods with Applications to Clinical Trials*. Chapman & Hall/CRC.\n- Moyé, L.A. (2006). *Multiple Analyses in Clinical Trials: Fundamentals for Investigators*. Springer.\n",
    "supporting": [
      "bs08-advanced-biostatistics_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}