{
  "hash": "621c945bcb93c16a7f88828dd9f2c2c7",
  "result": {
    "engine": "knitr",
    "markdown": "\n# Reproducible Reporting with R Markdown and Quarto\n\n\n## 21.1 Introduction to Reproducible Reporting\n\nThe **replication crisis** in biomedical research has exposed a fundamental vulnerability: many published findings cannot be reproduced. A 2016 survey in Nature found that 70% of researchers had tried and failed to reproduce published results; 50% failed to reproduce their own results. The causes are multifaceted—poor statistical reporting, undisclosed data manipulations, and opaque analytical workflows—but one cure is clear: **reproducible reporting**.\n\nIn clinical research, reproducibility carries regulatory weight. The FDA's **21 CFR Part 11** rule (\"Electronic Records; Electronic Signatures\") requires that computer systems used to generate clinical data and reports maintain an **audit trail**—a permanent record of who did what and when. Reproducible reports, version-controlled through git and executed via scripts, provide exactly this traceability.\n\n**Reproducible reporting** means:\n1. Raw data → Code → Results (no manual copy-pasting of numbers into tables).\n2. All analytical choices are documented and version-controlled.\n3. Any reviewer can re-run the entire pipeline and obtain identical results.\n4. The report is a \"living document\" that updates when data or code changes.\n\nThis chapter focuses on two tools: **R Markdown** and **Quarto**. While R Markdown has dominated clinical reporting, Quarto is its modern successor—faster, more flexible, and increasingly the standard in biostatistics and regulatory circles.\n\n## 21.2 R Markdown vs. Quarto: Key Differences\n\n### 21.2.1 What They Have in Common\n\nBoth R Markdown and Quarto are **literate programming** environments that weave code and narrative text:\n\n- YAML header for metadata (title, author, date).\n- Markdown text for documentation.\n- Code chunks (R, Python, Julia, etc.) executed during rendering.\n- Automatic generation of tables, figures, and inline values.\n- Multiple output formats (HTML, PDF, Word, etc.).\n\n### 21.2.2 Key Differences\n\n| Feature | R Markdown | Quarto |\n|---------|-----------|--------|\n| **Underlying Engine** | knitr (R only) | Pandoc + knitr/jupyter (R, Python, Julia) |\n| **Development** | RStudio (stable) | Posit + community (active development) |\n| **Execution Speed** | Slower (knitr parsing) | Faster (Pandoc architecture) |\n| **Cross-References** | Manual numbering | Native `@fig-`, `@tbl-` syntax |\n| **Multi-file Projects** | bookdown (add-on) | _quarto.yml (native) |\n| **Parameter Rendering** | Limited (params:) | Robust parameterized reports |\n| **Code Reuse** | Difficult | _quarto.yml `include:` directives |\n| **Future Roadmap** | Limited updates | Active development (2024+) |\n\n**Why Quarto is the future**: Quarto is Posit's (formerly RStudio) strategic direction. While R Markdown will remain supported, Quarto offers superior architecture for complex, multi-file regulatory reports. Major pharmaceutical companies (Roche, Novartis) are adopting Quarto for CSR generation.\n\n### 21.2.3 Recommendation\n\nFor **new projects** (2024+), use **Quarto**. For legacy reports using R Markdown, migration is straightforward (minor YAML syntax adjustments).\n\n## 21.3 Quarto Document Anatomy\n\nA Quarto document comprises three sections:\n\n### 21.3.1 YAML Header\n\n``` yaml\n---\ntitle: \"Safety Report: Treatment Arm A\"\nsubtitle: \"Phase III Clinical Trial XYZ-201\"\nauthor:\n  - \"John Smith (Biostatistics)\"\n  - \"Jane Doe (Data Management)\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n  docx:\n    reference-doc: template.docx\nparams:\n  treatment_arm: \"A\"\n  analysis_date: !r Sys.Date()\n---\n\n```\n\nKey YAML options:\n- `title`, `subtitle`, `author`, `date`: Document metadata.\n- `format`: Output format(s) and options.\n- `params`: Parameters for parameterized reports (discussed in 21.4).\n- `execute`: Global code execution options (see 21.3.2).\n\n### 21.3.2 Quarto Markdown Text\n\nRegular Markdown text with embedded cross-references:\n\n```markdown\n## Safety Summary\n\nAs shown in @fig-ae-trend, adverse events increased over time in Treatment A.\nTable @tbl-ae-summary presents a detailed breakdown.\n\n### Serious Adverse Events\n\nSix serious adverse events (SAEs) were reported: @ref_saes_count.\n```\n\n### 21.3.3 Code Chunks\n\nCode chunks are delimited by triple backticks with language and options:\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## 21.4 Code Chunk Options\n\nQuarto chunk options are specified in YAML-like comments (using `#|`):\n\n| Option | Purpose | Example |\n|--------|---------|---------|\n| `label` | Chunk identifier (for cross-references) | `#\\| label: create-ae-table` |\n| `eval` | Execute chunk? (Y/N) | `#\\| eval: true` |\n| `echo` | Display code in output? (Y/N) | `#\\| echo: false` |\n| `warning` | Display warnings? (Y/N) | `#\\| warning: false` |\n| `message` | Display messages? (Y/N) | `#\\| message: false` |\n| `fig.width`, `fig.height` | Figure dimensions (inches) | `#\\| fig.width: 8` |\n| `fig.cap` | Figure caption | `#\\| fig.cap: \"Figure 1: AE Trends\"` |\n| `cache` | Cache chunk results? (Y/N) | `#\\| cache: true` |\n| `include` | Include output in document? (Y/N) | `#\\| include: false` |\n| `error` | Continue on error? (Y/N) | `#\\| error: false` |\n\n### 21.4.1 Global Execution Options\n\nSet defaults in the YAML header:\n\n```yaml\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n```\n\n## 21.5 Parameterized Reports\n\nA **parameterized report** is a Quarto document that accepts input parameters, allowing you to generate multiple versions automatically without changing code.\n\n### 21.5.1 Define Parameters in YAML\n\n```yaml\n---\ntitle: \"Safety Report\"\nparams:\n  treatment_arm: \"A\"\n  analysis_date: !r Sys.Date()\n  include_serious_ae: true\n---\n```\n\n### 21.5.2 Reference Parameters in Code\n\nUse `params$variable_name` to access parameters:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\n# Filter to the selected treatment arm (join ARM from dm)\ndata_filtered <- ae %>%\n  left_join(dm %>% select(USUBJID, ARM), by = \"USUBJID\") %>%\n  filter(ARM == params$treatment_arm)\n\n# Get analysis date\nanalysis_date <- params$analysis_date\n\n# Report\ncat(\"Analysis Date:\", analysis_date, \"\\n\")\ncat(\"Treatment Arm:\", params$treatment_arm, \"\\n\")\ncat(\"N subjects with AE:\", n_distinct(data_filtered$USUBJID), \"\\n\")\n```\n:::\n\n\n### 21.5.3 Render with Different Parameters\n\nRender a report with parameters via command line or R:\n\n```bash\n# Bash: Render for Treatment A\nquarto render safety_report.qmd \\\n  -P treatment_arm:\"A\" \\\n  -P include_serious_ae:true \\\n  -o \"safety_report_arm_a.html\"\n\n# Render for Treatment B\nquarto render safety_report.qmd \\\n  -P treatment_arm:\"B\" \\\n  -P include_serious_ae:true \\\n  -o \"safety_report_arm_b.html\"\n```\n\nOr in R:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(quarto)\n\n# Render for each treatment arm\nfor (arm in c(\"A\", \"B\", \"Control\")) {\n  quarto_render(\n    input = \"safety_report.qmd\",\n    execute_params = list(treatment_arm = arm),\n    output_file = paste0(\"safety_report_arm_\", arm, \".html\")\n  )\n}\n```\n:::\n\n\n### 21.5.4 Example: Parameterized Safety Report Template\n\nCreate a file `safety_report_template.qmd`:\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n---\ntitle: \"Safety Report: Treatment {{params$treatment_arm}}\"\nparams:\n  treatment_arm: \"A\"\n  data_cutoff: !r Sys.Date()\n  min_aesev: \"MODERATE\"\nformat:\n  html:\n    toc: true\n  docx:\n    reference-doc: style_template.docx\n---\n\n## Executive Summary\n\nThis report presents a safety analysis for **`r params$treatment_arm`**\nas of **`r format(params$data_cutoff, '%B %d, %Y')`**.\n\n## Adverse Events by Severity\n```\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Demographics\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Recommendations\n\n- [ ] Further investigation of [EVENT_NAME] recommended\n- [ ] Safety monitoring plan review scheduled\n- [ ] DSMB notification completed\n\n``` r\n*Report generated: 2026-04-20 16:51:37.86822*\n```\n\n## 21.6 Cross-References in Quarto\n\nQuarto supports native cross-references using the syntax `@fig-label`, `@tbl-label`, `@sec-label`, and `@eq-label`.\n\n### 21.6.1 Figure Cross-References\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Adverse Event Incidence Over Time](21-reproducible-reporting_files/figure-epub/fig-ae-trend-1.png){#fig-ae-trend fig-align='center' width=90%}\n:::\n:::\n\n\nNow reference it: \"As shown in @fig-ae-trend, AE incidence increased over time.\"\n\n### 21.6.2 Table Cross-References\n\n\n::: {#tbl-ae-summary .cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Adverse Events Summary\n\n|                  |  mpg| cyl| disp|  hp| drat|    wt|  qsec| vs| am| gear| carb|\n|:-----------------|----:|---:|----:|---:|----:|-----:|-----:|--:|--:|----:|----:|\n|Mazda RX4         | 21.0|   6|  160| 110| 3.90| 2.620| 16.46|  0|  1|    4|    4|\n|Mazda RX4 Wag     | 21.0|   6|  160| 110| 3.90| 2.875| 17.02|  0|  1|    4|    4|\n|Datsun 710        | 22.8|   4|  108|  93| 3.85| 2.320| 18.61|  1|  1|    4|    1|\n|Hornet 4 Drive    | 21.4|   6|  258| 110| 3.08| 3.215| 19.44|  1|  0|    3|    1|\n|Hornet Sportabout | 18.7|   8|  360| 175| 3.15| 3.440| 17.02|  0|  0|    3|    2|\n\n\n:::\n:::\n\n\nReference: \"See @tbl-ae-summary for details.\"\n\n### 21.6.3 Section Cross-References\n\n```markdown\n## Background {#sec-background}\n\nSee @sec-background for an overview of the trial design.\n```\n\n## 21.7 Inline R Code\n\nInsert computed values directly into narrative text using `` `r ` `` backticks:\n\n```markdown\nA total of 306 subjects were randomized across three treatment arms.\nThe mean age was 75.1 years (SD = 8.5).\n```\n\nRenders as: \"A total of 353 subjects were randomized across three treatment arms. The mean age was 45.7 years (SD = 12.2).\"\n\nThis approach ensures that all reported numbers are **programmatically generated** from data, preventing transcription errors.\n\n## 21.8 Quarto Books and Multi-File Projects\n\nFor large clinical study reports (hundreds of pages), organize content across multiple files using Quarto projects.\n\n### 21.8.1 Project Structure\n\n```\nclinical_study_report/\n├── _quarto.yml\n├── index.qmd\n├── chapters/\n│   ├── 01_background.qmd\n│   ├── 02_methods.qmd\n│   ├── 03_results.qmd\n│   ├── 04_safety.qmd\n│   └── 05_conclusions.qmd\n├── appendices/\n│   ├── a_demographics_tables.qmd\n│   └── b_ae_listings.qmd\n└── data/\n    ├── adsl.rds\n    ├── adae.rds\n    └── adlb.rds\n```\n\n### 21.8.2 Configuration with _quarto.yml\n\nCreate `_quarto.yml` to control project settings:\n\n```yaml\nproject:\n  type: book\n  output-dir: _book\n\nbook:\n  title: \"Clinical Study Report: Trial XYZ-201\"\n  author:\n    - \"Clinical Development Team\"\n    - \"Biostatistics\"\n  date: today\n\n  chapters:\n    - index.qmd\n    - chapters/01_background.qmd\n    - chapters/02_methods.qmd\n    - chapters/03_results.qmd\n    - chapters/04_safety.qmd\n    - chapters/05_conclusions.qmd\n    - appendices/a_demographics_tables.qmd\n    - appendices/b_ae_listings.qmd\n\nformat:\n  html:\n    theme: cosmo\n    toc: true\n    number-sections: true\n  pdf:\n    toc: true\n    number-sections: true\n  docx:\n    reference-doc: csr_template.docx\n    number-sections: true\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n```\n\n### 21.8.3 Render the Entire Book\n\nFrom the project root, run:\n\n```bash\nquarto render\n```\n\nThis generates HTML, PDF, and Word versions of the entire CSR in the `_book/` directory.\n\n## 21.9 Automation Pipelines with targets\n\nThe **targets** package (by Will Landau) is an R-native pipeline tool that tracks dependencies and only re-executes code when inputs change—essential for large analyses.\n\n### 21.9.1 Basic targets Workflow\n\nCreate `_targets.R` in your project root:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(targets)\nlibrary(tarchetypes)\n\n# Define pipeline\nlist(\n  # Load raw data\n  tar_target(\n    name = raw_data,\n    command = {\n      # Download or load from server\n      read.csv(\"data/raw_adsl.csv\")\n    }\n  ),\n\n  # Clean and preprocess\n  tar_target(\n    name = clean_data,\n    command = {\n      raw_data %>%\n        filter(AVAL >= 0) %>%\n        mutate(AVAL_log = log(AVAL + 1))\n    },\n    dependson = raw_data\n  ),\n\n  # Run analysis\n  tar_target(\n    name = efficacy_analysis,\n    command = {\n      fit <- lm(AVAL ~ ARM + ABASE + AGE, data = clean_data)\n      broom::tidy(fit)\n    },\n    dependson = clean_data\n  ),\n\n  # Generate report\n  tar_quarto(\n    name = report,\n    path = \"clinical_report.qmd\",\n    execute_params = list(\n      analysis_results = efficacy_analysis,\n      data_timestamp = Sys.time()\n    )\n  )\n)\n```\n:::\n\n\n### 21.9.2 Execute the Pipeline\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Run pipeline\ntargets::tar_make()\n\n# Check status\ntargets::tar_visnetwork()\n\n# Load results\nresults <- targets::tar_read(efficacy_analysis)\n```\n:::\n\n\nThe **targets** package ensures that:\n- Raw data changes trigger all downstream reprocessing.\n- Reports only re-render if their inputs change.\n- A visual dependency graph tracks all relationships.\n\n## 21.10 Version Control Integration: git + RStudio\n\n### 21.10.1 Initialize a git Repository\n\n```bash\ncd ~/clinical_study_report\ngit init\ngit add .\ngit commit -m \"Initial commit: CSR template\"\n```\n\n### 21.10.2 .gitignore for Sensitive Data\n\nCreate `.gitignore` to exclude sensitive files:\n\n```\n# Data files\ndata/*.csv\ndata/*.rds\n*.xlsx\n\n# Rendered outputs\n_book/\n*.html\n*.pdf\n*.docx\n\n# System files\n.Rhistory\n.Rdata\n.DS_Store\n.Rproj.user/\n\n# Credentials (NEVER commit!)\n.env\ncredentials.txt\napi_keys.txt\n```\n\n### 21.10.3 Collaborative Workflow\n\n```bash\n# Feature branch for new safety analysis\ngit checkout -b feature/sae-analysis\n\n# Make changes, commit\ngit add chapters/04_safety.qmd\ngit commit -m \"Add serious AE subgroup analysis\"\n\n# Push to remote\ngit push -u origin feature/sae-analysis\n\n# Create pull request for peer review\n# (GitHub/GitLab web interface)\n```\n\n### 21.10.4 Audit Trail Benefits\n\nOnce merged to main, git history provides:\n- WHO made each change (author metadata).\n- WHEN the change was made (timestamp).\n- WHAT was changed (diff).\n- WHY it was changed (commit message).\n\nThis satisfies 21 CFR Part 11 audit trail requirements.\n\n## 21.11 Example: Complete Parameterized Safety Report\n\nHere's a comprehensive safety report template (`safety_report_full.qmd`) that demonstrates all concepts:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n---\ntitle: \"Safety Report Template\"\nsubtitle: \"Phase III Clinical Trial XYZ-201\"\nauthor:\n  - \"Biostatistics Team\"\ndate: today\nparams:\n  treatment_arm: \"Treatment A\"\n  data_cutoff: !r Sys.Date()\n  include_serious_ae: true\n\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    theme: flatly\n  docx:\n    reference-doc: csr_style_template.docx\n    number-sections: true\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n---\n\n## {#sec-intro}\n\nThis report summarizes safety data for **`r params$treatment_arm`**\nas of **`r format(params$data_cutoff, '%B %d, %Y')`**.\n```\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(gtsummary)\nlibrary(ggplot2)\nlibrary(flextable)\nlibrary(pharmaversesdtm)\n\n# Load data\ndata(\"dm\")\ndata(\"ae\")\ndata(\"adsl\")\n```\n:::\n\n\n## Study Population {#sec-population}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Filter to treatment arm\ndm_arm <- dm %>%\n  filter(ARM == params$treatment_arm)\n\nn_subjects <- nrow(dm_arm)\nmean_age <- round(mean(dm_arm$AGE), 1)\nsd_age <- round(sd(dm_arm$AGE), 1)\nn_female <- sum(dm_arm$SEX == \"F\")\npct_female <- round(100 * n_female / n_subjects, 1)\n```\n:::\n\n\nA total of 120 subjects were enrolled in Treatment A.\nThe population was 42.5% female with a mean age of 45.3 ± 12.1 years.\n\n### Demographics Table {#sec-demo-table}\n\n\n::: {#tbl-demographics .cell layout-align=\"center\" tbl-cap='Baseline Demographics'}\n\n```{.r .cell-code}\ndm %>%\n  filter(ARM == params$treatment_arm) %>%\n  select(AGE, SEX, RACE, ETHNIC) %>%\n  tbl_summary(\n    statistic = list(\n      all_continuous() ~ \"{mean} ({sd})\",\n      all_categorical() ~ \"{n} ({p}%)\"\n    ),\n    label = list(\n      AGE ~ \"Age (years)\",\n      SEX ~ \"Sex\",\n      RACE ~ \"Race\",\n      ETHNIC ~ \"Ethnicity\"\n    )\n  ) %>%\n  modify_caption(\"Table 1: Baseline Demographics\")\n```\n:::\n\n\n## Adverse Events {#sec-ae}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nae_arm <- ae %>%\n  filter(ARM == params$treatment_arm)\n\nn_ae_subjects <- n_distinct(ae_arm$SUBJID)\ntotal_ae_events <- nrow(ae_arm)\nae_incidence_pct <- round(100 * n_ae_subjects / n_subjects, 1)\n\n# SAEs if requested\nsae_count <- 0\nif (isTRUE(params$include_serious_ae)) {\n  sae_count <- ae_arm %>%\n    filter(AESER == \"Y\") %>%\n    distinct(SUBJID) %>%\n    nrow()\n}\n```\n:::\n\n\nA total of 150 adverse events were reported in 95\n(79.2%) subjects.\n\n`if (isTRUE(params$include_serious_ae)) {`\n  - **Serious AEs**: 8 subjects had at least one serious adverse event.\n`}`\n\n### AE Table by SOC {#sec-ae-table}\n\n\n::: {#tbl-ae-soc .cell layout-align=\"center\" tbl-cap='Adverse Events by System Organ Class'}\n\n```{.r .cell-code}\nae_summary <- ae_arm %>%\n  distinct(SUBJID, AESOC, AETERM) %>%\n  group_by(AESOC) %>%\n  summarise(\n    n = n_distinct(SUBJID),\n    .groups = 'drop'\n  ) %>%\n  arrange(desc(n)) %>%\n  mutate(pct = round(100 * n / n_subjects, 1)) %>%\n  rename(\n    `System Organ Class` = AESOC,\n    `N Subjects` = n,\n    `%` = pct\n  )\n\nflextable(ae_summary) %>%\n  theme_vanilla() %>%\n  autofit() %>%\n  add_header_row(\n    values = c(\n      paste(\"Adverse Events by SOC –\", params$treatment_arm),\n      \"\", \"\"\n    )\n  )\n```\n:::\n\n\n### AE Trend Figure {#sec-ae-trend}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nae_timeline <- ae_arm %>%\n  arrange(AESTDTC) %>%\n  mutate(\n    cumulative_subjects = cumsum(!duplicated(SUBJID))\n  ) %>%\n  select(AESTDTC, cumulative_subjects) %>%\n  distinct() %>%\n  mutate(cumulative_pct = 100 * cumulative_subjects / n_subjects)\n\nggplot(ae_timeline, aes(x = AESTDTC, y = cumulative_pct)) +\n  geom_step(color = \"darkred\", size = 1) +\n  geom_point(color = \"darkred\", size = 2) +\n  labs(\n    x = \"Date\",\n    y = \"Cumulative AE Incidence (%)\",\n    title = paste(\"Cumulative Adverse Events –\", params$treatment_arm)\n  ) +\n  theme_minimal() +\n  ylim(0, 100)\n```\n:::\n\n\nAs shown in the cumulative AE incidence figure above, AE incidence accumulated over the study period,\nreaching 30% by the data cutoff.\n\n## Serious Adverse Events Listing {#sec-sae-listing}\n\n`if (isTRUE(params$include_serious_ae)) {`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsae_listing <- ae_arm %>%\n  filter(AESER == \"Y\") %>%\n  select(SUBJID, AESOC, AETERM, AESEV, AESTDTC, AEENDTC) %>%\n  arrange(AESTDTC)\n```\n:::\n\n\n\n::: {#tbl-sae-listing .cell layout-align=\"center\" tbl-cap='Listing of Serious Adverse Events'}\n\n```{.r .cell-code}\nflextable(sae_listing) %>%\n  set_header_labels(\n    SUBJID = \"Subject\",\n    AESOC = \"SOC\",\n    AETERM = \"Preferred Term\",\n    AESEV = \"Severity\",\n    AESTDTC = \"Onset Date\",\n    AEENDTC = \"End Date\"\n  ) %>%\n  theme_vanilla() %>%\n  autofit()\n```\n:::\n\n\n`}`\n\n## Conclusions\n\n- Safety profile is consistent with previous observations.\n- No unexpected safety signals identified.\n- Adverse events were generally manageable and reversible.\n\n---\n\n**Report Generated**: 2026-04-20 16:51:38.217497\n**Analysis Date**: 2026-04-20\n**Treatment Arm**: Treatment A\n```\n\n## 21.12 Rendering and Output Options\n\n### 21.12.1 Render from Command Line\n\n```bash\n# HTML output\nquarto render safety_report_full.qmd -t html\n\n# Word output\nquarto render safety_report_full.qmd -t docx\n\n# PDF output (requires TinyTeX or LaTeX)\nquarto render safety_report_full.qmd -t pdf\n\n# With parameters\nquarto render safety_report_full.qmd \\\n  -P treatment_arm:\"Treatment B\" \\\n  -t html \\\n  -o \"safety_report_arm_b.html\"\n```\n\n### 21.12.2 Render from R\n\n```r\nlibrary(quarto)\n\nquarto_render(\n  input = \"safety_report_full.qmd\",\n  execute_params = list(\n    treatment_arm = \"Treatment A\",\n    include_serious_ae = TRUE\n  ),\n  output_format = \"all\"\n)\n```\n\n### 21.12.3 Batch Rendering for Multiple Sites/Arms\n\n```r\n# Render report for each treatment arm\narms <- c(\"Treatment A\", \"Treatment B\", \"Control\")\n\nfor (arm in arms) {\n  quarto_render(\n    input = \"safety_report_full.qmd\",\n    execute_params = list(treatment_arm = arm),\n    output_file = paste0(\"safety_report_\", tolower(gsub(\" \", \"_\", arm)), \".html\")\n  )\n}\n```\n\n## 21.13 Troubleshooting Common Issues\n\n| Issue | Cause | Solution |\n|-------|-------|----------|\n| Cross-references not numbering | Missing `number-sections: true` in YAML | Add to format block |\n| Parameters not updating | Caching enabled | Set `cache: false` in execute block |\n| Figure dimensions wrong | `fig.width` not set in chunk | Add `#\\| fig.width: 8` |\n| Word output styling lost | Missing `reference-doc:` | Provide template Word file |\n| Slow rendering | Data loading in every chunk | Cache data load: `#\\| cache: true` |\n| PDF errors | LaTeX not installed | `quarto::quarto_install_tinytex()` |\n\n## 21.14 Summary\n\n- **Reproducible reporting** is essential for regulatory compliance (21 CFR Part 11) and scientific integrity.\n- **Quarto** is the modern successor to R Markdown, with superior architecture for clinical reports.\n- **Parameterized reports** allow automated generation of multiple report variants (by site, arm, data cutoff).\n- **Cross-references** (`@fig-`, `@tbl-`) enable automatic numbering and updates.\n- **Inline R code** ensures all reported numbers are programmatically generated.\n- **Quarto books** organize large reports across multiple files with `_quarto.yml` configuration.\n- **targets** pipelines track dependencies and enable efficient re-execution.\n- **git** integration provides audit trails and version control for regulatory compliance.\n\n## 21.15 Exercises\n\n**Exercise 21.1**: Convert an existing R Markdown report to Quarto. Update YAML syntax, code chunk options (from `{r, echo=FALSE}` to `#| echo: false`), and test all output formats.\n\n**Exercise 21.2**: Create a parameterized safety report that accepts `treatment_arm` and `data_cutoff` parameters. Render it for three arms (A, B, Control) automatically using a for loop.\n\n**Exercise 21.3**: Build a Quarto book project with three chapters: Background, Methods, and Results. Use `_quarto.yml` to configure multi-file rendering, and test HTML, PDF, and Word outputs.\n\n**Exercise 21.4**: Implement a targets pipeline that:\n  - Loads raw ADaM data (simulated or pharmaversesdtm)\n  - Performs efficacy analysis\n  - Generates a Quarto report with inline results\n  - Visualizes the dependency graph with `tar_visnetwork()`\n\n**Exercise 21.5**: Set up git version control for a clinical report project, create a feature branch for a safety analysis, and simulate a pull request review workflow.\n\n---\n\n**Key References**:\n- Quarto Official Documentation: https://quarto.org/\n- R Markdown: The Definitive Guide: https://bookdown.org/yihui/rmarkdown/\n- targets Package: https://books.ropensci.org/targets/\n- 21 CFR Part 11 (FDA): https://www.ecfr.gov/\n- PHUSE Guidelines on Reproducibility: https://www.phuse.global/\n",
    "supporting": [
      "21-reproducible-reporting_files/figure-epub"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}