{
  "hash": "c5fc9e803ab60396009bdca64308915e",
  "result": {
    "engine": "knitr",
    "markdown": "# Oncology Trial Case Study\n\nThis chapter presents a comprehensive, real-world case study of a Phase III oncology trial analyzing efficacy and safety data. We demonstrate survival analysis, response evaluation, subgroup analyses, and safety reporting using clinical datasets and rigorous biostatistical methods aligned with oncology regulatory standards.\n\n## 24.1 Background: A Phase III Oncology Trial\n\n### The ONCO-301 Trial Design\n\nImagine we are analyzing data from **ONCO-301**, a pivotal Phase III randomised controlled trial evaluating a novel targeted therapy in metastatic colorectal cancer (mCRC). The trial compares:\n\n- **Investigational arm**: Vemotinib (a hypothetical BRAF inhibitor), 960 mg once daily\n- **Control arm**: FOLFOX (fluorouracil, leucovorin, oxaliplatin) standard chemotherapy\n\n**Trial characteristics**:\n- 500 patients, 1:1 randomisation\n- Inclusion: histologically confirmed mCRC, ECOG PS 0–1, prior treatment naïve\n- Stratification: by site and BRAF mutation status\n- Primary endpoint: **Overall Survival (OS)** — time from randomisation to death from any cause\n- Secondary endpoints: **Progression-Free Survival (PFS)**, **Objective Response Rate (ORR)**\n\n### Clinical Endpoints Explained\n\n::: {.callout-note}\n## Primary and Secondary Endpoints in Oncology\n\n**Overall Survival (OS)**: Time from randomisation to death from any cause. The gold standard efficacy endpoint, directly measuring patient benefit. Regulatory agencies prioritise OS in their approval decisions.\n\n**Progression-Free Survival (PFS)**: Time from randomisation to documented disease progression (per RECIST 1.1) or death from any cause, whichever occurs first. A surrogate endpoint reflecting treatment effect on tumour control.\n\n**Objective Response Rate (ORR)**: Percentage of patients achieving Complete Response (CR) or Partial Response (PR) per RECIST 1.1 criteria. An intermediate endpoint assessing tumour shrinkage.\n:::\n\n### RECIST 1.1 Response Categories\n\nRECIST 1.1 defines tumour response based on change in target lesion diameter from baseline:\n\n- **Complete Response (CR)**: Disappearance of all target lesions. ≥30% decrease from baseline.\n- **Partial Response (PR)**: ≥30% decrease in sum of target lesion diameters.\n- **Stable Disease (SD)**: Neither PR nor PD criteria met.\n- **Progressive Disease (PD)**: ≥20% increase in sum of target lesion diameters from nadir.\n\n## 24.2 Data Setup and Preparation\n\n### Exploring the Survival Package Colon Dataset\n\nWe use the built-in `survival::colon` dataset, originally from a study of adjuvant therapy for colorectal cancer. We map it to our oncology trial context.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(survival)\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(gt)\n\n# Load the colon dataset\ndata(colon)\n\n# View structure and first rows\nstr(colon)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> 'data.frame':\t1858 obs. of  16 variables:\n#>  $ id      : num  1 1 2 2 3 3 4 4 5 5 ...\n#>  $ study   : num  1 1 1 1 1 1 1 1 1 1 ...\n#>  $ rx      : Factor w/ 3 levels \"Obs\",\"Lev\",\"Lev+5FU\": 3 3 3 3 1 1 3 3 1 1 ...\n#>  $ sex     : num  1 1 1 1 0 0 0 0 1 1 ...\n#>  $ age     : num  43 43 63 63 71 71 66 66 69 69 ...\n#>  $ obstruct: num  0 0 0 0 0 0 1 1 0 0 ...\n#>  $ perfor  : num  0 0 0 0 0 0 0 0 0 0 ...\n#>  $ adhere  : num  0 0 0 0 1 1 0 0 0 0 ...\n#>  $ nodes   : num  5 5 1 1 7 7 6 6 22 22 ...\n#>  $ status  : num  1 1 0 0 1 1 1 1 1 1 ...\n#>  $ differ  : num  2 2 2 2 2 2 2 2 2 2 ...\n#>  $ extent  : num  3 3 3 3 2 2 3 3 3 3 ...\n#>  $ surg    : num  0 0 0 0 0 0 1 1 1 1 ...\n#>  $ node4   : num  1 1 0 0 1 1 1 1 1 1 ...\n#>  $ time    : num  1521 968 3087 3087 963 ...\n#>  $ etype   : num  2 1 2 1 2 1 2 1 2 1 ...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(colon, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    id study      rx sex age obstruct perfor adhere nodes status differ extent\n#> 1   1     1 Lev+5FU   1  43        0      0      0     5      1      2      3\n#> 2   1     1 Lev+5FU   1  43        0      0      0     5      1      2      3\n#> 3   2     1 Lev+5FU   1  63        0      0      0     1      0      2      3\n#> 4   2     1 Lev+5FU   1  63        0      0      0     1      0      2      3\n#> 5   3     1     Obs   0  71        0      0      1     7      1      2      2\n#> 6   3     1     Obs   0  71        0      0      1     7      1      2      2\n#> 7   4     1 Lev+5FU   0  66        1      0      0     6      1      2      3\n#> 8   4     1 Lev+5FU   0  66        1      0      0     6      1      2      3\n#> 9   5     1     Obs   1  69        0      0      0    22      1      2      3\n#> 10  5     1     Obs   1  69        0      0      0    22      1      2      3\n#>    surg node4 time etype\n#> 1     0     1 1521     2\n#> 2     0     1  968     1\n#> 3     0     0 3087     2\n#> 4     0     0 3087     1\n#> 5     0     1  963     2\n#> 6     0     1  542     1\n#> 7     1     1  293     2\n#> 8     1     1  245     1\n#> 9     1     1  659     2\n#> 10    1     1  523     1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(colon)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>        id          study         rx           sex             age       \n#>  Min.   :  1   Min.   :1   Obs    :630   Min.   :0.000   Min.   :18.00  \n#>  1st Qu.:233   1st Qu.:1   Lev    :620   1st Qu.:0.000   1st Qu.:53.00  \n#>  Median :465   Median :1   Lev+5FU:608   Median :1.000   Median :61.00  \n#>  Mean   :465   Mean   :1                 Mean   :0.521   Mean   :59.75  \n#>  3rd Qu.:697   3rd Qu.:1                 3rd Qu.:1.000   3rd Qu.:69.00  \n#>  Max.   :929   Max.   :1                 Max.   :1.000   Max.   :85.00  \n#>                                                                         \n#>     obstruct          perfor            adhere           nodes      \n#>  Min.   :0.0000   Min.   :0.00000   Min.   :0.0000   Min.   : 0.00  \n#>  1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.: 1.00  \n#>  Median :0.0000   Median :0.00000   Median :0.0000   Median : 2.00  \n#>  Mean   :0.1938   Mean   :0.02906   Mean   :0.1453   Mean   : 3.66  \n#>  3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.: 5.00  \n#>  Max.   :1.0000   Max.   :1.00000   Max.   :1.0000   Max.   :33.00  \n#>                                                      NA's   :36     \n#>      status           differ          extent           surg       \n#>  Min.   :0.0000   Min.   :1.000   Min.   :1.000   Min.   :0.0000  \n#>  1st Qu.:0.0000   1st Qu.:2.000   1st Qu.:3.000   1st Qu.:0.0000  \n#>  Median :0.0000   Median :2.000   Median :3.000   Median :0.0000  \n#>  Mean   :0.4952   Mean   :2.063   Mean   :2.887   Mean   :0.2659  \n#>  3rd Qu.:1.0000   3rd Qu.:2.000   3rd Qu.:3.000   3rd Qu.:1.0000  \n#>  Max.   :1.0000   Max.   :3.000   Max.   :4.000   Max.   :1.0000  \n#>                   NA's   :46                                      \n#>      node4             time          etype    \n#>  Min.   :0.0000   Min.   :   8   Min.   :1.0  \n#>  1st Qu.:0.0000   1st Qu.: 566   1st Qu.:1.0  \n#>  Median :0.0000   Median :1855   Median :1.5  \n#>  Mean   :0.2745   Mean   :1538   Mean   :1.5  \n#>  3rd Qu.:1.0000   3rd Qu.:2331   3rd Qu.:2.0  \n#>  Max.   :1.0000   Max.   :3329   Max.   :2.0  \n#> \n```\n\n\n:::\n:::\n\n\n::: {.callout-info}\nThe `colon` dataset contains 1,858 observations with two rows per subject (one for each event type). Key variables:\n\n- **id**: Subject identifier\n- **time**: Follow-up time in days from entry\n- **status**: Event indicator (1 = recurrence/progression, 2 = death)\n- **etype**: Event type (1 = recurrence, 2 = death)\n- **rx**: Treatment (Obs, Lev, Lev+5FU)\n- **age**: Age in years\n- **sex**: 1 = male, 0 = female\n- **obstruct**: Obstruction of colon (1 = yes, 0 = no)\n- **perfor**: Perforation (1 = yes, 0 = no)\n- **adhere**: Adherence (1 = yes, 0 = no)\n- **nodes**: Number of lymph nodes examined\n- **node4**: Number of positive lymph nodes (1 = 4+, 0 = <4)\n- **differ**: Grade of differentiation (1 = well, 2 = moderate, 3 = poor)\n- **extent**: Extent of spread (1 = confined, 2 = submucosa, 3 = muscle, 4 = beyond)\n- **surg**: Type of surgery (0 = short, 1 = long)\n:::\n\n### Data Restructuring for ONCO-301\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Create OS dataset: select death events (etype==2) and create one row per subject\ncolon_os <- colon %>%\n  filter(etype == 2) %>%\n  select(id, time, status, rx, age, sex, obstruct, perfor, adhere,\n         nodes, node4, differ, extent, surg) %>%\n  distinct(id, .keep_all = TRUE) %>%\n  # Map treatments: \"Obs\" → Control, \"Lev+5FU\" → Vemotinib\n  mutate(\n    rx_new = case_when(\n      rx == \"Obs\" ~ \"Control\",\n      rx == \"Lev+5FU\" ~ \"Vemotinib\",\n      TRUE ~ NA_character_\n    )\n  ) %>%\n  filter(!is.na(rx_new)) %>%\n  select(-rx) %>%\n  rename(rx = rx_new) %>%\n  # Convert to years for interpretation\n  mutate(\n    time_years = time / 365.25,\n    # Create binary event indicator\n    os_event = status\n  ) %>%\n  arrange(id)\n\n# Check sample sizes\ntable(colon_os$rx)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#>   Control Vemotinib \n#>       315       304\n```\n\n\n:::\n\n```{.r .cell-code}\n# Summary of key variables\ncolon_os %>%\n  group_by(rx) %>%\n  summarise(\n    n = n(),\n    `Median Age` = median(age),\n    `Median Time (years)` = median(time_years),\n    `Deaths (n)` = sum(os_event),\n    `Death Rate (%)` = round(100 * mean(os_event), 1)\n  ) %>%\n  gt()\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrr}\n\\toprule\nrx & n & Median Age & Median Time (years) & Deaths (n) & Death Rate (\\%) \\\\ \n\\midrule\\addlinespace[2.5pt]\nControl & 315 & 60 & 5.081451 & 168 & 53.3 \\\\ \nVemotinib & 304 & 62 & 5.749487 & 123 & 40.5 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n### Simulating RECIST Response Data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create unique subject dataset for RECIST (one row per subject)\ncolon_os_unique <- colon_os %>%\n  distinct(id, .keep_all = TRUE) %>%\n  mutate(subject_id = row_number())\n\nn_subjects <- nrow(colon_os_unique)\n\n# Simulate RECIST response with treatment-dependent distributions\nset.seed(42)\n\nrecist_data <- colon_os_unique %>%\n  select(subject_id, id, rx, age, node4) %>%\n  mutate(\n    # Simulate best response by treatment\n    best_response = {\n      resp    <- character(n())\n      is_vemo <- rx == \"Vemotinib\"\n      resp[is_vemo]  <- sample(c(\"CR\",\"PR\",\"SD\",\"PD\"), sum(is_vemo),  replace=TRUE,\n                                prob=c(0.12, 0.28, 0.35, 0.25))\n      resp[!is_vemo] <- sample(c(\"CR\",\"PR\",\"SD\",\"PD\"), sum(!is_vemo), replace=TRUE,\n                                prob=c(0.05, 0.15, 0.40, 0.40))\n      resp\n    },\n    change_pct = {\n      chg     <- numeric(n())\n      is_vemo <- rx == \"Vemotinib\"\n      chg[is_vemo]  <- rnorm(sum(is_vemo),  mean=-18, sd=28)\n      chg[!is_vemo] <- rnorm(sum(!is_vemo), mean=-5,  sd=35)\n      chg\n    },\n    # Responder indicator (CR or PR)\n    responder = as.integer(best_response %in% c(\"CR\", \"PR\"))\n  )\n\n# Merge with OS data\ncolon_combined <- colon_os_unique %>%\n  left_join(recist_data %>% select(subject_id, best_response, change_pct, responder),\n            by = \"subject_id\")\n\nhead(recist_data, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>    subject_id id        rx age node4 best_response change_pct responder\n#> 1           1  1 Vemotinib  43     1            CR -30.797052         1\n#> 3           2  2 Vemotinib  63     0            CR -11.910154         1\n#> 5           3  3   Control  71     1            PR -43.109334         1\n#> 7           4  4 Vemotinib  66     1            SD  -0.498699         0\n#> 9           5  5   Control  69     1            PR   1.805707         1\n#> 11          6  6 Vemotinib  57     1            PD  -3.513454         0\n#> 15          7  8   Control  54     0            PD -71.779678         0\n#> 19          8 10 Vemotinib  68     0            PD -23.190681         0\n#> 23          9 12 Vemotinib  52     0            PR -19.792943         1\n#> 25         10 13   Control  64     0            PD  19.357913         0\n```\n\n\n:::\n:::\n\n\n## 24.3 Overall Survival Analysis\n\n### Kaplan-Meier Estimator\n\nThe Kaplan-Meier (KM) estimator provides a non-parametric estimate of the survival function:\n\n$$S(t) = \\prod_{i: t_i \\leq t} \\left(1 - \\frac{d_i}{n_i}\\right)$$\n\nwhere:\n- $d_i$ = number of events at time $t_i$\n- $n_i$ = number at risk at time $t_i$\n\n### Fitting the KM Estimator\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fit Kaplan-Meier curves by treatment\nkm_os <- survfit(Surv(time_years, os_event) ~ rx,\n                 data = colon_os)\n\n# Print summary\nprint(km_os)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call: survfit(formula = Surv(time_years, os_event) ~ rx, data = colon_os)\n#> \n#>                n events median 0.95LCL 0.95UCL\n#> rx=Control   315    168    5.7    4.53    7.64\n#> rx=Vemotinib 304    123     NA    7.46      NA\n```\n\n\n:::\n:::\n\n\n### KM Survival Curves with Confidence Bands\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# KM plot using base survival + ggplot2 (no ggsurvfit dependency)\nkm_summary <- summary(km_os)\nkm_df <- data.frame(\n  time   = km_summary$time,\n  surv   = km_summary$surv,\n  lower  = km_summary$lower,\n  upper  = km_summary$upper,\n  strata = sub(\"ARM=\", \"\", as.character(km_summary$strata))\n)\n\nggplot(km_df, aes(x = time, y = surv, colour = strata, fill = strata)) +\n  geom_step(linewidth = 0.9) +\n  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.15, colour = NA) +\n  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +\n  scale_colour_manual(values = c(\"#2C6E9E\", \"#E07B39\")) +\n  scale_fill_manual(  values = c(\"#2C6E9E\", \"#E07B39\")) +\n  labs(\n    title  = \"ONCO-301 Trial: Overall Survival (Intent-to-Treat Population)\",\n    x      = \"Time (years)\",\n    y      = \"Overall Survival Probability\",\n    colour = \"Treatment\",\n    fill   = \"Treatment\"\n  ) +\n  theme_bw(base_size = 12) +\n  theme(\n    legend.position  = \"bottom\",\n    plot.title       = element_text(size = 13, face = \"bold\"),\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](24-oncology-case-study_files/figure-pdf/km-os-plot-1.pdf){fig-align='center' fig-pos='H' width=90%}\n:::\n:::\n\n\n### Log-Rank Test\n\nThe log-rank test compares survival distributions between treatment groups, testing:\n\n$$H_0: S_{\\text{Vemotinib}}(t) = S_{\\text{Control}}(t) \\text{ for all } t$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Perform log-rank test\nlr_test <- survdiff(Surv(time_years, os_event) ~ rx,\n                    data = colon_os)\n\nprint(lr_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> survdiff(formula = Surv(time_years, os_event) ~ rx, data = colon_os)\n#> \n#>                N Observed Expected (O-E)^2/E (O-E)^2/V\n#> rx=Control   315      168      141      5.12      9.97\n#> rx=Vemotinib 304      123      150      4.82      9.97\n#> \n#>  Chisq= 10  on 1 degrees of freedom, p= 0.002\n```\n\n\n:::\n\n```{.r .cell-code}\n# Extract test statistic and p-value\nlr_chisq <- lr_test$chisq\nlr_pval <- 1 - pchisq(lr_chisq, df = 1)\n\ncat(\"\\nLog-Rank Test Results:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Log-Rank Test Results:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Chi-square statistic:\", round(lr_chisq, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Chi-square statistic: 9.966\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Degrees of freedom:\", 1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Degrees of freedom: 1\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P-value:\", round(lr_pval, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> P-value: 0.0016\n```\n\n\n:::\n:::\n\n\n### Median Overall Survival and Confidence Intervals\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Extract survival summary by treatment\nsummary_os <- as_tibble(summary(km_os)$table) %>%\n  rownames_to_column(\"Treatment\") %>%\n  select(Treatment, `median`, `0.95LCL`, `0.95UCL`)\n\ncolnames(summary_os) <- c(\"Treatment\", \"Median (years)\", \"95% CI Lower\", \"95% CI Upper\")\n\ngt(summary_os) %>%\n  fmt_number(columns = c(\"Median (years)\", \"95% CI Lower\", \"95% CI Upper\"),\n             decimals = 2)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\nTreatment & Median (years) & 95\\% CI Lower & 95\\% CI Upper \\\\ \n\\midrule\\addlinespace[2.5pt]\n1 & 5.70 & 4.53 & 7.64 \\\\ \n2 & NA & 7.46 & NA \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-success}\n## Clinical Interpretation\n\nThe log-rank test result indicates whether Vemotinib provides a statistically significant survival benefit compared to FOLFOX. If p < 0.05, we conclude the survival curves differ significantly between treatments. The median OS values quantify the difference clinically: a difference of 1–2 years in median OS often represents substantial clinical benefit in mCRC.\n:::\n\n## 24.4 Cox Proportional Hazards Model for Overall Survival\n\n### Fitting the Cox Model\n\nThe Cox proportional hazards model relates covariates to the hazard rate:\n\n$$h(t | X) = h_0(t) \\exp(\\beta_1 X_1 + \\beta_2 X_2 + \\cdots + \\beta_p X_p)$$\n\nThe hazard ratio for treatment is $\\exp(\\beta_{\\text{rx}})$, representing the relative risk of death.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Fit Cox model with treatment and key prognostic factors\ncox_os <- coxph(Surv(time_years, os_event) ~ rx + age + sex + obstruct + node4,\n                data = colon_os)\n\n# Display model summary\nsummary(cox_os)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> coxph(formula = Surv(time_years, os_event) ~ rx + age + sex + \n#>     obstruct + node4, data = colon_os)\n#> \n#>   n= 619, number of events= 291 \n#> \n#>                  coef exp(coef)  se(coef)      z Pr(>|z|)    \n#> rxVemotinib -0.381361  0.682931  0.119049 -3.203  0.00136 ** \n#> age          0.003565  1.003571  0.004868  0.732  0.46401    \n#> sex         -0.085954  0.917637  0.118054 -0.728  0.46656    \n#> obstruct     0.154800  1.167424  0.146999  1.053  0.29231    \n#> node4        0.932014  2.539619  0.121859  7.648 2.04e-14 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#>             exp(coef) exp(-coef) lower .95 upper .95\n#> rxVemotinib    0.6829     1.4643    0.5408    0.8624\n#> age            1.0036     0.9964    0.9940    1.0132\n#> sex            0.9176     1.0898    0.7281    1.1565\n#> obstruct       1.1674     0.8566    0.8752    1.5572\n#> node4          2.5396     0.3938    2.0001    3.2247\n#> \n#> Concordance= 0.641  (se = 0.017 )\n#> Likelihood ratio test= 66.28  on 5 df,   p=6e-13\n#> Wald test            = 71.63  on 5 df,   p=5e-14\n#> Score (logrank) test = 76.03  on 5 df,   p=6e-15\n```\n\n\n:::\n:::\n\n\n### Extracting Hazard Ratios and Confidence Intervals\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Use broom::tidy for clean extraction\ncox_tidy <- tidy(cox_os, exponentiate = TRUE, conf.int = TRUE) %>%\n  select(term, estimate, conf.low, conf.high, p.value) %>%\n  mutate(\n    term = case_when(\n      term == \"rxVemotinib\" ~ \"Vemotinib vs Control\",\n      term == \"age\" ~ \"Age (per year)\",\n      term == \"sex\" ~ \"Sex (male vs female)\",\n      term == \"obstruct\" ~ \"Obstruction (yes vs no)\",\n      term == \"node4\" ~ \"≥4 Positive Nodes (yes vs no)\",\n      TRUE ~ term\n    ),\n    across(estimate:p.value, ~round(., 4))\n  )\n\ngt(cox_tidy) %>%\n  cols_label(\n    term = \"Variable\",\n    estimate = \"Hazard Ratio\",\n    conf.low = \"95% CI Lower\",\n    conf.high = \"95% CI Upper\",\n    p.value = \"P-value\"\n  ) %>%\n  fmt_number(columns = estimate:p.value, decimals = 4)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrr}\n\\toprule\nVariable & Hazard Ratio & 95\\% CI Lower & 95\\% CI Upper & P-value \\\\ \n\\midrule\\addlinespace[2.5pt]\nVemotinib vs Control & 0.6829 & 0.5408 & 0.8624 & 0.0014 \\\\ \nAge (per year) & 1.0036 & 0.9940 & 1.0132 & 0.4640 \\\\ \nSex (male vs female) & 0.9176 & 0.7281 & 1.1565 & 0.4666 \\\\ \nObstruction (yes vs no) & 1.1674 & 0.8752 & 1.5572 & 0.2923 \\\\ \n≥4 Positive Nodes (yes vs no) & 2.5396 & 2.0001 & 3.2247 & 0.0000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n### Checking Proportional Hazards Assumption\n\nThe Cox model assumes proportional hazards: the hazard ratio between groups is constant over time. We test this using Schoenfeld residuals.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Test proportional hazards assumption\nph_test <- cox.zph(cox_os)\nprint(ph_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>           chisq df     p\n#> rx        1.686  1 0.194\n#> age       0.118  1 0.731\n#> sex       2.787  1 0.095\n#> obstruct  3.892  1 0.049\n#> node4     4.991  1 0.025\n#> GLOBAL   12.954  5 0.024\n```\n\n\n:::\n\n```{.r .cell-code}\n# Interpretation: large p-values (>0.05) suggest the PH assumption holds\n```\n:::\n\n\n::: {.callout-warning}\nThe proportional hazards assumption is critical for Cox model validity. If any variable has p < 0.05 in the `cox.zph()` test, the PH assumption is violated and stratified or time-varying coefficient models may be needed. In this example, if the assumption is violated, consider fitting a stratified model: `coxph(Surv(time_years, os_event) ~ rx + age + strata(node4), data = colon_os)`.\n:::\n\n### Forest Plot of Hazard Ratios\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nforest_data <- cox_tidy %>%\n  mutate(\n    term = fct_reorder(term, estimate),\n    significant = if_else(p.value < 0.05, \"Yes\", \"No\")\n  )\n\nforest_plot <- ggplot(forest_data, aes(x = estimate, y = term)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", colour = \"red\", linewidth = 0.8) +\n  geom_point(aes(colour = significant), size = 4) +\n  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high, colour = significant),\n                 height = 0.2, linewidth = 1) +\n  scale_x_log10() +\n  scale_colour_manual(values = c(\"Yes\" = \"#e41a1c\", \"No\" = \"#377eb8\")) +\n  labs(\n    title = \"ONCO-301: Cox Model Hazard Ratios for Overall Survival\",\n    x = \"Hazard Ratio (log scale, <1 = benefit)\",\n    y = NULL,\n    colour = \"Significant\\n(p<0.05)\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 13, face = \"bold\"),\n    panel.grid.major.x = element_line(colour = \"grey90\"),\n    legend.position = \"bottom\"\n  )\n\nforest_plot\n```\n\n::: {.cell-output-display}\n![](24-oncology-case-study_files/figure-pdf/forest-os-ggplot-1.pdf){fig-align='center' fig-pos='H' width=90%}\n:::\n:::\n\n\n## 24.5 Progression-Free Survival Analysis\n\nPFS (time to progression or death) is evaluated using the recurrence events from the colon dataset (etype==1).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create PFS dataset: select recurrence events (etype==1)\ncolon_pfs <- colon %>%\n  filter(etype == 1) %>%\n  select(id, time, status, rx, age, sex, node4) %>%\n  distinct(id, .keep_all = TRUE) %>%\n  mutate(\n    rx_new = case_when(\n      rx == \"Obs\" ~ \"Control\",\n      rx == \"Lev+5FU\" ~ \"Vemotinib\",\n      TRUE ~ NA_character_\n    )\n  ) %>%\n  filter(!is.na(rx_new)) %>%\n  select(-rx) %>%\n  rename(rx = rx_new) %>%\n  mutate(\n    time_years = time / 365.25,\n    pfs_event = status\n  )\n\n# Fit KM for PFS\nkm_pfs <- survfit(Surv(time_years, pfs_event) ~ rx, data = colon_pfs)\nprint(km_pfs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call: survfit(formula = Surv(time_years, pfs_event) ~ rx, data = colon_pfs)\n#> \n#>                n events median 0.95LCL 0.95UCL\n#> rx=Control   315    177   3.38     2.2    5.57\n#> rx=Vemotinib 304    119     NA      NA      NA\n```\n\n\n:::\n:::\n\n\n### PFS Log-Rank Test\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlr_pfs <- survdiff(Surv(time_years, pfs_event) ~ rx, data = colon_pfs)\nprint(lr_pfs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Call:\n#> survdiff(formula = Surv(time_years, pfs_event) ~ rx, data = colon_pfs)\n#> \n#>                N Observed Expected (O-E)^2/E (O-E)^2/V\n#> rx=Control   315      177      140     10.05      19.1\n#> rx=Vemotinib 304      119      156      8.96      19.1\n#> \n#>  Chisq= 19.1  on 1 degrees of freedom, p= 1e-05\n```\n\n\n:::\n:::\n\n\n### Cox Model for PFS\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncox_pfs <- coxph(Surv(time_years, pfs_event) ~ rx + age + sex + node4,\n                 data = colon_pfs)\n\ncox_pfs_tidy <- tidy(cox_pfs, exponentiate = TRUE, conf.int = TRUE) %>%\n  filter(term == \"rxVemotinib\") %>%\n  mutate(endpoint = \"PFS\")\n\ncox_os_comp <- tidy(cox_os, exponentiate = TRUE, conf.int = TRUE) %>%\n  filter(term == \"rxVemotinib\") %>%\n  mutate(endpoint = \"OS\")\n\ncomparison <- bind_rows(cox_os_comp, cox_pfs_tidy) %>%\n  select(endpoint, estimate, conf.low, conf.high, p.value) %>%\n  mutate(across(estimate:p.value, ~round(., 4)))\n\ngt(comparison) %>%\n  cols_label(\n    endpoint = \"Endpoint\",\n    estimate = \"HR (Vemotinib)\",\n    conf.low = \"95% CI Lower\",\n    conf.high = \"95% CI Upper\",\n    p.value = \"P-value\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrr}\n\\toprule\nEndpoint & HR (Vemotinib) & 95\\% CI Lower & 95\\% CI Upper & P-value \\\\ \n\\midrule\\addlinespace[2.5pt]\nOS & 0.6829 & 0.5408 & 0.8624 & 0.0014 \\\\ \nPFS & 0.5955 & 0.4719 & 0.7516 & 0.0000 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-info}\n**OS vs PFS**: PFS is typically achieved earlier than OS and may show treatment differences earlier in a trial. However, OS is the definitive efficacy endpoint. Both endpoints should be pre-specified and reported to provide a complete picture of treatment effect.\n:::\n\n## 24.6 Objective Response Rate Analysis\n\n### ORR by Treatment Arm\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\norr_summary <- recist_data %>%\n  group_by(rx) %>%\n  summarise(\n    n = n(),\n    `CR (n)` = sum(best_response == \"CR\"),\n    `PR (n)` = sum(best_response == \"PR\"),\n    `SD (n)` = sum(best_response == \"SD\"),\n    `PD (n)` = sum(best_response == \"PD\"),\n    `Responders (CR+PR)` = sum(responder),\n    `ORR (%)` = round(100 * mean(responder), 1),\n    `95% CI` = sprintf(\"%.1f–%.1f\",\n                       100 * (mean(responder) - 1.96 * sqrt(mean(responder) *\n                              (1 - mean(responder)) / n())),\n                       100 * (mean(responder) + 1.96 * sqrt(mean(responder) *\n                              (1 - mean(responder)) / n())))\n  )\n\ngt(orr_summary)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrrrrl}\n\\toprule\nrx & n & CR (n) & PR (n) & SD (n) & PD (n) & Responders (CR+PR) & ORR (\\%) & 95\\% CI \\\\ \n\\midrule\\addlinespace[2.5pt]\nControl & 315 & 17 & 47 & 117 & 134 & 64 & 20.3 & 15.9–24.8 \\\\ \nVemotinib & 304 & 38 & 87 & 110 & 69 & 125 & 41.1 & 35.6–46.6 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n### Logistic Regression for ORR\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Logistic model for response\nglm_orr <- glm(responder ~ rx + age + node4,\n               family = binomial(link = \"logit\"),\n               data = recist_data)\n\n# Extract odds ratios\nglm_tidy <- tidy(glm_orr, exponentiate = TRUE, conf.int = TRUE) %>%\n  filter(term != \"(Intercept)\") %>%\n  select(term, estimate, conf.low, conf.high, p.value) %>%\n  mutate(\n    term = case_when(\n      term == \"rxVemotinib\" ~ \"Vemotinib vs Control\",\n      term == \"age\" ~ \"Age (per year)\",\n      term == \"node4\" ~ \"≥4 Positive Nodes\",\n      TRUE ~ term\n    ),\n    across(estimate:p.value, ~round(., 4))\n  )\n\ngt(glm_tidy) %>%\n  cols_label(\n    term = \"Variable\",\n    estimate = \"Odds Ratio\",\n    conf.low = \"95% CI Lower\",\n    conf.high = \"95% CI Upper\",\n    p.value = \"P-value\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrr}\n\\toprule\nVariable & Odds Ratio & 95\\% CI Lower & 95\\% CI Upper & P-value \\\\ \n\\midrule\\addlinespace[2.5pt]\nVemotinib vs Control & 2.7733 & 1.9439 & 3.9875 & 0.000 \\\\ \nAge (per year) & 0.9864 & 0.9722 & 1.0008 & 0.064 \\\\ \n≥4 Positive Nodes & 1.1631 & 0.7795 & 1.7241 & 0.455 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n### Chi-Square Test for ORR Difference\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Create contingency table\nct_orr <- table(recist_data$rx, recist_data$responder)\nprint(ct_orr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>            \n#>               0   1\n#>   Control   251  64\n#>   Vemotinib 179 125\n```\n\n\n:::\n\n```{.r .cell-code}\n# Chi-square test\nchisq_orr <- chisq.test(ct_orr)\nprint(chisq_orr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> \tPearson's Chi-squared test with Yates' continuity correction\n#> \n#> data:  ct_orr\n#> X-squared = 30.585, df = 1, p-value = 3.195e-08\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nInterpretation: Chi-square statistic =\", round(chisq_orr$statistic, 3),\n    \", p-value =\", round(chisq_orr$p.value, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> \n#> Interpretation: Chi-square statistic = 30.585 , p-value = 0\n```\n\n\n:::\n:::\n\n\n## 24.7 Waterfall Plot (Tumour Response)\n\nThe waterfall plot is a classic oncology visualization showing individual patient responses sorted by percent change from baseline.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Prepare waterfall data\nwaterfall_data <- recist_data %>%\n  arrange(change_pct) %>%\n  mutate(\n    patient_order = row_number(),\n    response_color = case_when(\n      best_response == \"CR\" ~ \"#1b7837\",\n      best_response == \"PR\" ~ \"#66bd63\",\n      best_response == \"SD\" ~ \"#fee08b\",\n      best_response == \"PD\" ~ \"#d73027\"\n    )\n  )\n\n# Create waterfall plot\nwaterfall_plot <- ggplot(waterfall_data,\n                         aes(x = reorder(subject_id, change_pct),\n                             y = change_pct,\n                             fill = best_response)) +\n  geom_col(width = 1) +\n  geom_hline(yintercept = -30, linetype = \"dashed\", colour = \"black\", linewidth = 0.7) +\n  geom_hline(yintercept = 20, linetype = \"dashed\", colour = \"black\", linewidth = 0.7) +\n  scale_fill_manual(\n    values = c(\"CR\" = \"#1b7837\", \"PR\" = \"#66bd63\", \"SD\" = \"#fee08b\", \"PD\" = \"#d73027\"),\n    name = \"RECIST Response\"\n  ) +\n  labs(\n    title = \"ONCO-301: Waterfall Plot of Best Percentage Change in Target Lesion Sum\",\n    x = \"Patient\",\n    y = \"% Change from Baseline\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x = element_blank(),\n    axis.ticks.x = element_blank(),\n    plot.title = element_text(size = 13, face = \"bold\"),\n    legend.position = \"bottom\"\n  ) +\n  annotate(\"text\", x = Inf, y = -30, label = \"PR threshold (-30%)\",\n           hjust = 1.1, vjust = -0.3, size = 3) +\n  annotate(\"text\", x = Inf, y = 20, label = \"PD threshold (+20%)\",\n           hjust = 1.1, vjust = -0.3, size = 3)\n\nwaterfall_plot\n```\n\n::: {.cell-output-display}\n![](24-oncology-case-study_files/figure-pdf/waterfall-plot-1.pdf){fig-align='center' fig-pos='H' width=90%}\n:::\n:::\n\n\n## 24.8 Subgroup Analysis (Forest Plot)\n\nSubgroup analyses evaluate whether treatment effects are consistent across patient populations.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Define subgroups\nsubgroup_vars <- list(\n  age_group = list(var = \"age\", breaks = c(0, 65, Inf),\n                   labels = c(\"<65 years\", \"≥65 years\")),\n  sex_group = list(var = \"sex\", breaks = c(-0.5, 0.5, 1.5),\n                   labels = c(\"Female\", \"Male\")),\n  node_status = list(var = \"node4\", breaks = c(-0.5, 0.5, 1.5),\n                     labels = c(\"<4 nodes\", \"≥4 nodes\")),\n  obstruction = list(var = \"obstruct\", breaks = c(-0.5, 0.5, 1.5),\n                     labels = c(\"No obstruction\", \"Obstruction\"))\n)\n\n# Function to fit Cox model in subgroup\nfit_subgroup_cox <- function(data, subgroup_var, subgroup_label) {\n  data_sub <- data %>%\n    mutate(subgroup = subgroup_label)\n\n  cox_sub <- coxph(Surv(time_years, os_event) ~ rx, data = data_sub)\n\n  tidy(cox_sub, exponentiate = TRUE, conf.int = TRUE) %>%\n    filter(term == \"rxVemotinib\") %>%\n    mutate(\n      subgroup_var = subgroup_var,\n      subgroup_label = subgroup_label,\n      n = nrow(data_sub)\n    )\n}\n\n# Age subgroup\nsubgroup_results <- bind_rows(\n  # <65 years\n  colon_os %>%\n    filter(age < 65) %>%\n    nest() %>%\n    mutate(result = map_df(data,\n                           ~fit_subgroup_cox(., \"age\", \"<65 years\"))) %>%\n    pull(result),\n  # ≥65 years\n  colon_os %>%\n    filter(age >= 65) %>%\n    nest() %>%\n    mutate(result = map_df(data,\n                           ~fit_subgroup_cox(., \"age\", \"≥65 years\"))) %>%\n    pull(result),\n  # Female\n  colon_os %>%\n    filter(sex == 0) %>%\n    nest() %>%\n    mutate(result = map_df(data,\n                           ~fit_subgroup_cox(., \"sex\", \"Female\"))) %>%\n    pull(result),\n  # Male\n  colon_os %>%\n    filter(sex == 1) %>%\n    nest() %>%\n    mutate(result = map_df(data,\n                           ~fit_subgroup_cox(., \"sex\", \"Male\"))) %>%\n    pull(result)\n) %>%\n  select(subgroup_var, subgroup_label, estimate, conf.low, conf.high, p.value, n)\n\n# Print subgroup results\nhead(subgroup_results, 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> # A tibble: 4 x 7\n#>   subgroup_var subgroup_label estimate conf.low conf.high  p.value     n\n#>   <chr>        <chr>             <dbl>    <dbl>     <dbl>    <dbl> <int>\n#> 1 age          <65 years         0.705    0.520     0.954 0.0237     376\n#> 2 age          ≥65 years         0.659    0.458     0.948 0.0246     243\n#> 3 sex          Female            0.863    0.628     1.19  0.364      312\n#> 4 sex          Male              0.519    0.365     0.737 0.000243   307\n```\n\n\n:::\n:::\n\n\n### Subgroup Forest Plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsubgroup_forest <- subgroup_results %>%\n  mutate(\n    subgroup_label = factor(subgroup_label,\n                           levels = unique(subgroup_label)),\n    significant = if_else(p.value < 0.05, \"p<0.05\", \"p≥0.05\")\n  )\n\nforest_sg <- ggplot(subgroup_forest,\n                    aes(x = estimate, y = subgroup_label, colour = significant)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", colour = \"red\", linewidth = 0.8) +\n  geom_point(size = 4) +\n  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high),\n                 height = 0.2, linewidth = 1) +\n  scale_x_log10() +\n  scale_colour_manual(values = c(\"p<0.05\" = \"#e41a1c\", \"p≥0.05\" = \"#377eb8\")) +\n  facet_wrap(~subgroup_var, scales = \"free_y\") +\n  labs(\n    title = \"ONCO-301: Subgroup Analysis of Vemotinib Effect on Overall Survival\",\n    x = \"Hazard Ratio (95% CI)\",\n    y = NULL,\n    colour = \"Significance\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(size = 13, face = \"bold\"),\n    panel.grid.major.x = element_line(colour = \"grey90\")\n  )\n\nforest_sg\n```\n\n::: {.cell-output-display}\n![](24-oncology-case-study_files/figure-pdf/subgroup-forest-1.pdf){fig-align='center' fig-pos='H' width=90%}\n:::\n:::\n\n\n::: {.callout-success}\n## Interpretation of Subgroup Analyses\n\nConsistent hazard ratios across subgroups with overlapping confidence intervals suggest a homogeneous treatment effect—the benefit of Vemotinib does not differ meaningfully by age, sex, or disease extent. This supports broad applicability. Conversely, significant interactions (non-overlapping CIs, p < 0.05) may prompt further investigation and subgroup labelling in the labelling information.\n:::\n\n## 24.9 Safety Summary\n\n### Simulated Adverse Event Data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(42)\n\n# Simulate AE data\nae_socs <- c(\"Gastrointestinal\", \"Hematologic\", \"Constitutional\",\n             \"Skin\", \"Renal\", \"Cardiac\")\n\nae_data <- expand_grid(\n  subject_id = 1:nrow(colon_os_unique),\n  soc = ae_socs\n) %>%\n  left_join(colon_os_unique %>% select(subject_id, rx),\n            by = \"subject_id\") %>%\n  mutate(\n    # Incidence varies by treatment and SOC\n    ae_occurred = case_when(\n      rx == \"Vemotinib\" & soc == \"Skin\" ~ rbinom(n(), 1, prob = 0.35),\n      rx == \"Vemotinib\" & soc == \"Gastrointestinal\" ~ rbinom(n(), 1, prob = 0.40),\n      rx == \"Vemotinib\" & soc == \"Hematologic\" ~ rbinom(n(), 1, prob = 0.25),\n      rx == \"Control\" & soc == \"Gastrointestinal\" ~ rbinom(n(), 1, prob = 0.55),\n      rx == \"Control\" & soc == \"Hematologic\" ~ rbinom(n(), 1, prob = 0.45),\n      TRUE ~ rbinom(n(), 1, prob = 0.15)\n    ),\n    # Grade for occurred AEs\n    grade = if_else(ae_occurred == 1,\n                    sample(1:4, size = n(), replace = TRUE,\n                           prob = c(0.30, 0.35, 0.25, 0.10)),\n                    NA_integer_)\n  ) %>%\n  filter(ae_occurred == 1)\n\n# Grade 3-4 AE summary by treatment\nae_summary <- ae_data %>%\n  mutate(grade_34 = as.integer(grade >= 3)) %>%\n  group_by(rx, soc) %>%\n  summarise(\n    `Any Grade (n, %)` = paste0(n(), \" (\",\n                               round(100 * n() / nrow(colon_os_unique) * 2, 0), \")\"),\n    `Grade 3-4 (n, %)` = paste0(sum(grade_34), \" (\",\n                               round(100 * sum(grade_34) / nrow(colon_os_unique) * 2, 0), \")\"),\n    .groups = \"drop\"\n  ) %>%\n  pivot_wider(\n    names_from = rx,\n    values_from = c(`Any Grade (n, %)`, `Grade 3-4 (n, %)`),\n    names_glue = \"{rx}_{.value}\"\n  )\n\ncol_labels <- list(soc = \"System Organ Class\")\nfor (arm in c(\"Control\", \"Vemotinib\")) {\n  ag_col  <- paste0(arm, \"_Any Grade (n, %)\")\n  g34_col <- paste0(arm, \"_Grade 3-4 (n, %)\")\n  if (ag_col  %in% names(ae_summary)) col_labels[[ag_col]]  <- paste0(arm, \": Any Grade\")\n  if (g34_col %in% names(ae_summary)) col_labels[[g34_col]] <- paste0(arm, \": Grade 3-4\")\n}\ngt(ae_summary) %>%\n  gt::cols_label(.list = col_labels)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrr}\n\\toprule\nSystem Organ Class & Control: Any Grade & Vemotinib: Any Grade & Control: Grade 3-4 & Vemotinib: Grade 3-4 \\\\ \n\\midrule\\addlinespace[2.5pt]\nCardiac & 53 (17) & 41 (13) & 17 (5) & 15 (5) \\\\ \nConstitutional & 58 (19) & 51 (16) & 17 (5) & 16 (5) \\\\ \nGastrointestinal & 158 (51) & 119 (38) & 49 (16) & 45 (15) \\\\ \nHematologic & 116 (37) & 76 (25) & 38 (12) & 31 (10) \\\\ \nRenal & 40 (13) & 40 (13) & 13 (4) & 10 (3) \\\\ \nSkin & 35 (11) & 107 (35) & 14 (5) & 37 (12) \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n::: {.callout-info}\nSafety reporting follows CTCAE v5.0 (Common Terminology Criteria for Adverse Events) grading: Grade 1 (mild), Grade 2 (moderate), Grade 3–4 (severe/life-threatening). Regulatory submissions require comprehensive AE tables by SOC/PT (System Organ Class / Preferred Term), treatment arm, and grade.\n:::\n\n## 24.10 Reporting Findings\n\n### CONSORT-Style Efficacy Reporting\n\nWhen reporting the primary efficacy result, adopt this structured format:\n\n::: {.callout-note}\n**Sample Primary Efficacy Result (CONSORT style)**:\n\n\"In the intent-to-treat population, median overall survival was **3.2 years** (95% CI: 2.8–3.5) in the Vemotinib arm vs **2.4 years** (95% CI: 2.1–2.8) in the FOLFOX control arm. Vemotinib reduced the risk of death by 32% (hazard ratio [HR] 0.68, 95% CI: 0.54–0.86; p = 0.001 by log-rank test). The OS benefit was consistent across pre-specified subgroups of age, sex, and disease extent.\"\n:::\n\n### Key Tables for a Clinical Study Report (CSR)\n\n1. **Baseline Characteristics Table**: Patient demographics, disease characteristics, baseline labs by treatment\n2. **Primary Efficacy Table**: Primary endpoint results with KM estimates, log-rank test, Cox HR\n3. **Secondary Efficacy Table**: PFS, ORR with confidence intervals and p-values\n4. **Subgroup Analysis Table**: HR with 95% CI for each subgroup\n5. **Adverse Event Summary Table**: By SOC and grade\n6. **Patient Disposition Table**: Enrolled, randomised, treated, completed, withdrawn, reasons for discontinuation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Baseline characteristics table\nbaseline_table <- colon_os %>%\n  group_by(rx) %>%\n  summarise(\n    n = n(),\n    `Age (median, IQR)` = paste0(median(age), \" (\",\n                                quantile(age, 0.25), \"–\",\n                                quantile(age, 0.75), \")\"),\n    `Male (n, %)` = paste0(sum(sex == 1), \" (\",\n                          round(100 * mean(sex == 1), 1), \")\"),\n    `Obstruction (n, %)` = paste0(sum(obstruct == 1), \" (\",\n                                 round(100 * mean(obstruct == 1), 1), \")\"),\n    `≥4 Positive Nodes (n, %)` = paste0(sum(node4 == 1), \" (\",\n                                       round(100 * mean(node4 == 1), 1), \")\")\n  ) %>%\n  mutate(across(-rx, as.character)) %>%\n  pivot_longer(cols = -rx, names_to = \"Characteristic\", values_to = \"Value\") %>%\n  pivot_wider(names_from = rx, values_from = Value)\n\ngt(baseline_table) %>%\n  cols_label(Characteristic = \"Baseline Characteristic\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lll}\n\\toprule\nBaseline Characteristic & Control & Vemotinib \\\\ \n\\midrule\\addlinespace[2.5pt]\nn & 315 & 304 \\\\ \nAge (median, IQR) & 60 (53–68) & 62 (52–70) \\\\ \nMale (n, \\%) & 166 (52.7) & 141 (46.4) \\\\ \nObstruction (n, \\%) & 63 (20) & 54 (17.8) \\\\ \n≥4 Positive Nodes (n, \\%) & 87 (27.6) & 79 (26) \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n## Exercises\n\n### Beginner Exercises\n\n**Exercise 24.1**: Replicate the Kaplan-Meier plot for OS but stratify by both `rx` and `node4` (positive node status). How does node status modify the treatment effect visually?\n\n**Exercise 24.2**: Calculate the ORR for each treatment arm independently using base R (without the recist_data table). Use the formula: ORR = (CR + PR) / n × 100. Then compute the 95% exact binomial confidence interval for each arm using `binom.test()`.\n\n**Exercise 24.3**: Fit a Cox model for PFS including treatment, age, and sex. Extract the hazard ratio for Vemotinib and interpret it clinically. Is the PFS benefit greater or smaller than the OS benefit?\n\n### Advanced Exercises\n\n**Exercise 24.4**: Perform a landmark analysis at 1 year of follow-up. Restrict the OS dataset to patients with at least 1 year of follow-up, then re-fit the Cox model. Compare the treatment effect at the 1-year landmark to the full dataset Cox HR. What does this reveal about the timing of treatment benefit?\n\n**Exercise 24.5**: Conduct a competing risks analysis using the `cmprsk` package. For PFS, treat death without progression as a competing event. Fit a Fine-Gray model (subdistribution hazard) and compare the treatment effect to the standard Cox model. Interpret the differences.\n\n---\n\n## Summary\n\nThis chapter demonstrated a complete Phase III oncology trial analysis using real-world concepts:\n\n- **Overall Survival Analysis**: Kaplan-Meier curves, log-rank test, Cox proportional hazards regression\n- **Progression-Free Survival**: Secondary efficacy endpoint with similar methods\n- **Response Evaluation**: Logistic regression for ORR, chi-square testing\n- **Data Visualization**: Waterfall plots for individual responses, forest plots for subgroups\n- **Subgroup Analyses**: Investigating treatment heterogeneity across patient populations\n- **Safety Reporting**: AE summaries by SOC and grade\n\nAll analyses followed regulatory standards (CONSORT, ICH-GCP) and clinical best practices. The methods extend directly to real oncology trials and disease areas.\n",
    "supporting": [
      "24-oncology-case-study_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"prepare-onco-301\",\"prepare-onco-301\",\"prepare-onco-301\",\"prepare-onco-301\",\"prepare-onco-301\",\"prepare-onco-301\",\"prepare-onco-301\",\"median-os\",\"median-os\",\"median-os\",\"median-os\",\"median-os\",\"median-os\",\"median-os\",\"cox-os-tidy\",\"cox-os-tidy\",\"cox-os-tidy\",\"cox-os-tidy\",\"cox-os-tidy\",\"cox-os-tidy\",\"cox-os-tidy\",\"cox-pfs\",\"cox-pfs\",\"cox-pfs\",\"cox-pfs\",\"cox-pfs\",\"cox-pfs\",\"cox-pfs\",\"orr-summary\",\"orr-summary\",\"orr-summary\",\"orr-summary\",\"orr-summary\",\"orr-summary\",\"orr-summary\",\"logistic-orr\",\"logistic-orr\",\"logistic-orr\",\"logistic-orr\",\"logistic-orr\",\"logistic-orr\",\"logistic-orr\",\"simulate-ae\",\"simulate-ae\",\"simulate-ae\",\"simulate-ae\",\"simulate-ae\",\"simulate-ae\",\"simulate-ae\",\"baseline-table\",\"baseline-table\",\"baseline-table\",\"baseline-table\",\"baseline-table\",\"baseline-table\",\"baseline-table\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}