{
  "hash": "59de3ffeda646fe3a0458d59d8099aa7",
  "result": {
    "engine": "knitr",
    "markdown": "# Sample Size and Power Calculations\n\n## Introduction\n\nSample size determination is one of the most consequential decisions in clinical trial design. An underpowered study risks missing a real treatment effect; an overpowered study wastes resources and exposes more patients than necessary to experimental treatments. Regulatory agencies require prospective justification of sample size in every confirmatory trial protocol.\n\nThis chapter covers:\n\n- **Fundamental concepts**: Effect size, power, Type I and II errors\n- **Two-sample t-test**: Continuous endpoints\n- **Two proportions**: Binary endpoints\n- **Survival endpoints**: Log-rank test and event-driven designs\n- **Equivalence and non-inferiority**: TOST and one-sided designs\n- **Multiple comparisons**: Adjusting for multiplicity\n- **Sensitivity analyses**: Handling uncertainty in design assumptions\n- **R packages**: `pwr`, `pwrss`, `gsDesign`, `rpact`\n\n---\n\n## 1. Core Concepts\n\n### 1.1 The Four Design Parameters\n\nAny sample size calculation involves four interdependent quantities. Fix any three and the fourth is determined:\n\n| Parameter | Symbol | Typical value |\n|---|---|---|\n| Significance level (Type I error rate) | $\\alpha$ | 0.05 (two-sided) |\n| Power (1 − Type II error rate) | $1-\\beta$ | 0.80 or 0.90 |\n| Effect size (standardised or absolute) | $\\delta$ | Clinically meaningful difference |\n| Sample size | $n$ | To be determined |\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(pwr)\nlibrary(gt)\nset.seed(42)\n\n# Illustrate power as a function of sample size\nalpha  <- 0.05\ndelta  <- 0.5    # medium standardised effect (Cohen's d)\nn_vals <- seq(10, 300, by = 5)\n\npower_vals <- sapply(n_vals, function(n) {\n  pwr.t.test(n = n, d = delta, sig.level = alpha,\n             type = \"two.sample\", alternative = \"two.sided\")$power\n})\n\ntibble(n = n_vals, power = power_vals) |>\n  ggplot(aes(x = n, y = power)) +\n  geom_line(colour = \"#2C6E9E\", linewidth = 1.1) +\n  geom_hline(yintercept = 0.80, linetype = \"dashed\", colour = \"#D32F2F\") +\n  geom_hline(yintercept = 0.90, linetype = \"dotted\", colour = \"#E07B39\") +\n  geom_vline(\n    xintercept = pwr.t.test(d = delta, sig.level = alpha,\n                             power = 0.80, type = \"two.sample\")$n,\n    linetype = \"dashed\", colour = \"#D32F2F\", alpha = 0.7\n  ) +\n  annotate(\"text\", x = 5, y = 0.82, label = \"80% power\",\n           colour = \"#D32F2F\", hjust = 0, size = 3.5) +\n  annotate(\"text\", x = 5, y = 0.92, label = \"90% power\",\n           colour = \"#E07B39\", hjust = 0, size = 3.5) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(\n    x     = \"Sample Size per Arm\",\n    y     = \"Power\",\n    title = \"Statistical Power vs. Sample Size\",\n    subtitle = paste0(\"Two-sample t-test, δ = \", delta, \" (Cohen's d), α = \", alpha)\n  ) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](bs07-sample-size-power_files/figure-pdf/power-setup-1.pdf){fig-align='center' fig-pos='H' width=90%}\n:::\n:::\n\n\n### 1.2 Effect Size: The Most Critical Input\n\nThe effect size must reflect the **minimum clinically important difference (MCID)** — the smallest difference that would matter to patients or clinicians — not the largest plausible effect.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nd_vals <- seq(0.1, 1.5, by = 0.05)\nn_needed <- sapply(d_vals, function(d) {\n  ceiling(pwr.t.test(d = d, sig.level = 0.05,\n                     power = 0.80, type = \"two.sample\")$n)\n})\n\ntibble(effect_size = d_vals, n_per_arm = n_needed) |>\n  ggplot(aes(x = effect_size, y = n_per_arm)) +\n  geom_line(colour = \"#2C6E9E\", linewidth = 1.1) +\n  geom_point(data = tibble(\n    effect_size = c(0.2, 0.5, 0.8),\n    n_per_arm   = c(\n      ceiling(pwr.t.test(d = 0.2, sig.level = 0.05, power = 0.80, type = \"two.sample\")$n),\n      ceiling(pwr.t.test(d = 0.5, sig.level = 0.05, power = 0.80, type = \"two.sample\")$n),\n      ceiling(pwr.t.test(d = 0.8, sig.level = 0.05, power = 0.80, type = \"two.sample\")$n)\n    ),\n    label = c(\"Small (0.2)\\nn=393\", \"Medium (0.5)\\nn=64\", \"Large (0.8)\\nn=26\")\n  ), aes(x = effect_size, y = n_per_arm), colour = \"#D32F2F\", size = 3) +\n  annotate(\"text\", x = c(0.2, 0.5, 0.8), y = c(450, 120, 80),\n           label = c(\"Small (0.2)\\nn=393\", \"Medium (0.5)\\nn=64\", \"Large (0.8)\\nn=26\"),\n           colour = \"#D32F2F\", size = 3) +\n  scale_y_log10(labels = scales::comma) +\n  labs(\n    x     = \"Standardised Effect Size (Cohen's d)\",\n    y     = \"Sample Size per Arm (log scale)\",\n    title = \"Effect Size Has a Dramatic Impact on Sample Size\",\n    subtitle = \"Two-sample t-test, 80% power, α = 0.05\"\n  ) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Sample size per arm as a function of effect size (two-sample t-test, 80% power, α = 0.05)](bs07-sample-size-power_files/figure-pdf/effect-size-impact-1.pdf){fig-align='center' fig-pos='H' width=90%}\n:::\n:::\n\n\n---\n\n## 2. Sample Size for Continuous Endpoints\n\n### 2.1 Two-Sample t-Test\n\nThe required sample size per arm:\n\n$$n = \\frac{2\\sigma^2(z_{\\alpha/2} + z_\\beta)^2}{\\delta^2}$$\n\nwhere $\\delta$ is the mean difference, $\\sigma$ is the common standard deviation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Example: Systolic blood pressure trial\n# MCID = 5 mmHg reduction; SD = 15 mmHg; α = 0.05 (two-sided); 90% power\n\ndelta_sbp <- 5       # MCID: 5 mmHg\nsigma_sbp <- 15      # assumed SD\nalpha_sbp <- 0.05\npower_sbp <- 0.90\n\nss_sbp <- pwr.t.test(\n  d          = delta_sbp / sigma_sbp,   # Cohen's d\n  sig.level  = alpha_sbp,\n  power      = power_sbp,\n  type       = \"two.sample\",\n  alternative = \"two.sided\"\n)\n\nn_sbp <- ceiling(ss_sbp$n)\n\ncat(\"=== SBP Trial Sample Size ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> === SBP Trial Sample Size ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"MCID (δ):      \", delta_sbp, \"mmHg\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> MCID (δ):       5 mmHg\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Assumed SD:    \", sigma_sbp, \"mmHg\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Assumed SD:     15 mmHg\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Cohen's d:     \", round(delta_sbp / sigma_sbp, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Cohen's d:      0.333\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"α (two-sided): \", alpha_sbp, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> α (two-sided):  0.05\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Power (1-β):   \", power_sbp, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Power (1-β):    0.9\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"n per arm:     \", n_sbp, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> n per arm:      191\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total N:       \", n_sbp * 2, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Total N:        382\n```\n\n\n:::\n\n```{.r .cell-code}\n# Sensitivity: vary SD assumption\ncat(\"Sensitivity to SD assumption:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Sensitivity to SD assumption:\n```\n\n\n:::\n\n```{.r .cell-code}\ntibble(\n  SD       = c(10, 12, 15, 18, 20),\n  n_per_arm = sapply(c(10, 12, 15, 18, 20), function(sd) {\n    ceiling(pwr.t.test(d = delta_sbp / sd, sig.level = alpha_sbp,\n                       power = power_sbp, type = \"two.sample\")$n)\n  }),\n  Total_N  = sapply(c(10, 12, 15, 18, 20), function(sd) {\n    2 * ceiling(pwr.t.test(d = delta_sbp / sd, sig.level = alpha_sbp,\n                            power = power_sbp, type = \"two.sample\")$n)\n  })\n) |>\n  mutate(Cohen_d = round(delta_sbp / SD, 3)) |>\n  gt() |>\n  tab_header(title = \"Sensitivity Analysis: Varying SD Assumption\",\n             subtitle = paste0(\"δ = \", delta_sbp, \" mmHg, α = \", alpha_sbp,\n                               \", power = \", power_sbp))\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Sensitivity Analysis: Varying SD Assumption\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  δ = 5 mmHg, α = 0.05, power = 0.9\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrrr}\n\\toprule\nSD & n\\_per\\_arm & Total\\_N & Cohen\\_d \\\\ \n\\midrule\\addlinespace[2.5pt]\n10 & 86 & 172 & 0.500 \\\\ \n12 & 123 & 246 & 0.417 \\\\ \n15 & 191 & 382 & 0.333 \\\\ \n18 & 274 & 548 & 0.278 \\\\ \n20 & 338 & 676 & 0.250 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n### 2.2 Power Curve\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nn_total_range <- seq(20, 400, by = 10)\npower_range   <- sapply(n_total_range, function(n_tot) {\n  pwr.t.test(n = n_tot / 2, d = delta_sbp / sigma_sbp,\n             sig.level = alpha_sbp, type = \"two.sample\")$power\n})\n\ntibble(n_total = n_total_range, power = power_range) |>\n  ggplot(aes(x = n_total, y = power)) +\n  geom_line(colour = \"#2C6E9E\", linewidth = 1.1) +\n  geom_hline(yintercept = c(0.80, 0.90), linetype = c(\"dashed\", \"dotted\"),\n             colour = c(\"#D32F2F\", \"#E07B39\")) +\n  geom_vline(xintercept = n_sbp * 2, linetype = \"dashed\",\n             colour = \"grey40\", alpha = 0.7) +\n  annotate(\"text\", x = n_sbp * 2 + 5, y = 0.5,\n           label = paste0(\"N = \", n_sbp * 2, \"\\n(90% power)\"),\n           hjust = 0, size = 3.5) +\n  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +\n  labs(\n    x     = \"Total Sample Size\",\n    y     = \"Power\",\n    title = \"Power Curve: SBP Reduction Trial\",\n    subtitle = paste0(\"δ = \", delta_sbp, \" mmHg, SD = \", sigma_sbp, \" mmHg\")\n  ) +\n  theme_bw(base_size = 12)\n```\n\n::: {.cell-output-display}\n![Power curve for SBP trial: power as a function of total sample size](bs07-sample-size-power_files/figure-pdf/power-curve-sbp-1.pdf){fig-align='center' fig-pos='H' width=90%}\n:::\n:::\n\n\n---\n\n## 3. Sample Size for Binary Endpoints\n\n### 3.1 Two-Proportion z-Test\n\nFor comparing two proportions $p_1$ and $p_2$:\n\n$$n = \\frac{(z_{\\alpha/2}\\sqrt{2\\bar{p}(1-\\bar{p})} + z_\\beta\\sqrt{p_1(1-p_1) + p_2(1-p_2)})^2}{(p_1 - p_2)^2}$$\n\nwhere $\\bar{p} = (p_1 + p_2)/2$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Example: response rate trial\np1 <- 0.55   # expected response rate (Active)\np2 <- 0.40   # expected response rate (Placebo)\nalpha_bin <- 0.05\npower_bin <- 0.80\n\nss_bin <- pwr.2p.test(\n  h          = ES.h(p1, p2),\n  sig.level  = alpha_bin,\n  power      = power_bin,\n  alternative = \"two.sided\"\n)\nn_bin <- ceiling(ss_bin$n)\n\ncat(\"=== Binary Endpoint Trial (Response Rate) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> === Binary Endpoint Trial (Response Rate) ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Active response rate (p1):  \", p1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Active response rate (p1):   0.55\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Placebo response rate (p2): \", p2, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Placebo response rate (p2):  0.4\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Difference:                 \", p1 - p2, \"(\", (p1 - p2) * 100, \"pp)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Difference:                  0.15 ( 15 pp)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Cohen's h:                  \", round(ES.h(p1, p2), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Cohen's h:                   0.3015\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"n per arm:                  \", n_bin, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> n per arm:                   173\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total N:                    \", n_bin * 2, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Total N:                     346\n```\n\n\n:::\n\n```{.r .cell-code}\n# Sensitivity: vary response rates\ncat(\"Sensitivity to assumed response rates:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Sensitivity to assumed response rates:\n```\n\n\n:::\n\n```{.r .cell-code}\nscenarios <- expand.grid(\n  p_active  = c(0.50, 0.55, 0.60),\n  p_placebo = c(0.35, 0.40, 0.45)\n) |>\n  filter(p_active > p_placebo) |>\n  mutate(\n    Diff      = round(p_active - p_placebo, 2),\n    n_per_arm = sapply(1:nrow(cur_data()), function(i) {\n      ceiling(pwr.2p.test(\n        h         = ES.h(p_active[i], p_placebo[i]),\n        sig.level = 0.05,\n        power     = 0.80\n      )$n)\n    }),\n    Total_N   = n_per_arm * 2\n  ) |>\n  rename(p_Active = p_active, p_Placebo = p_placebo)\n\nscenarios |>\n  gt() |>\n  tab_header(title = \"Sample Size Sensitivity: Binary Endpoint\",\n             subtitle = \"α = 0.05, power = 80%\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Sample Size Sensitivity: Binary Endpoint\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  α = 0.05, power = 80\\%\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrrrr}\n\\toprule\np\\_Active & p\\_Placebo & Diff & n\\_per\\_arm & Total\\_N \\\\ \n\\midrule\\addlinespace[2.5pt]\n0.50 & 0.35 & 0.15 & 170 & 340 \\\\ \n0.55 & 0.35 & 0.20 & 96 & 192 \\\\ \n0.60 & 0.35 & 0.25 & 62 & 124 \\\\ \n0.50 & 0.40 & 0.10 & 388 & 776 \\\\ \n0.55 & 0.40 & 0.15 & 173 & 346 \\\\ \n0.60 & 0.40 & 0.20 & 97 & 194 \\\\ \n0.50 & 0.45 & 0.05 & 1565 & 3130 \\\\ \n0.55 & 0.45 & 0.10 & 392 & 784 \\\\ \n0.60 & 0.45 & 0.15 & 173 & 346 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n---\n\n## 4. Sample Size for Survival Endpoints\n\n### 4.1 Event-Driven Designs\n\nSurvival trials are powered by the **number of events** (deaths, progressions), not the number of subjects. The required number of events for the log-rank test:\n\n$$E = \\frac{4(z_{\\alpha/2} + z_\\beta)^2}{[\\log(HR)]^2}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Survival trial: OS in oncology\n# HR = 0.70 (30% reduction in hazard); α = 0.05; power = 80%\nhr      <- 0.70\nalpha_s <- 0.05\npower_s <- 0.80\n\n# Required events (Schoenfeld formula)\nz_alpha <- qnorm(1 - alpha_s / 2)\nz_beta  <- qnorm(power_s)\ne_req   <- ceiling(4 * (z_alpha + z_beta)^2 / (log(hr))^2)\n\ncat(\"=== Survival Trial (Overall Survival) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> === Survival Trial (Overall Survival) ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Hazard Ratio (HR):     \", hr, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Hazard Ratio (HR):      0.7\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"α (two-sided):         \", alpha_s, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> α (two-sided):          0.05\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Power (1-β):           \", power_s, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Power (1-β):            0.8\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Required events:       \", e_req, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Required events:        247\n```\n\n\n:::\n\n```{.r .cell-code}\n# Translate events to subjects (assuming event probability)\n# Accrual = 24 months, follow-up = 12 months, control median OS = 18 months\nlambda_ctrl   <- log(2) / 18        # control arm hazard (median 18 months)\nlambda_active <- lambda_ctrl * hr   # active arm hazard\n\n# Probability of event by end of trial (36 months max)\nt_max <- 36\n# Simplified: event probability ~ 1 - exp(-lambda * t_max) averaged over uniform accrual\np_event_ctrl   <- 1 - exp(-lambda_ctrl   * t_max * 0.6)  # approximate\np_event_active <- 1 - exp(-lambda_active * t_max * 0.6)\np_event_avg    <- (p_event_ctrl + p_event_active) / 2\n\nn_subjects <- ceiling(e_req / p_event_avg)\n\ncat(\"Event probability (approx, per arm): \", round(p_event_avg, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Event probability (approx, per arm):  0.503\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Estimated subjects per arm:          \", ceiling(n_subjects / 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Estimated subjects per arm:           246\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total subjects:                      \", n_subjects, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Total subjects:                       492\n```\n\n\n:::\n\n```{.r .cell-code}\n# HR sensitivity table\nhr_vals <- c(0.60, 0.65, 0.70, 0.75, 0.80)\ntibble(\n  HR           = hr_vals,\n  Events_req   = sapply(hr_vals, function(h) {\n    ceiling(4 * (qnorm(0.975) + qnorm(0.80))^2 / (log(h))^2)\n  })\n) |>\n  gt() |>\n  tab_header(title = \"Events Required vs. Hazard Ratio\",\n             subtitle = \"α = 0.05 (two-sided), power = 80%\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Events Required vs. Hazard Ratio\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  α = 0.05 (two-sided), power = 80\\%\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rr}\n\\toprule\nHR & Events\\_req \\\\ \n\\midrule\\addlinespace[2.5pt]\n0.60 & 121 \\\\ \n0.65 & 170 \\\\ \n0.70 & 247 \\\\ \n0.75 & 380 \\\\ \n0.80 & 631 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n---\n\n## 5. Non-Inferiority and Equivalence Trials\n\n### 5.1 Non-Inferiority Margin\n\nNon-inferiority (NI) trials test that a new treatment is not worse than an active comparator by more than a pre-specified margin $\\Delta_{NI}$.\n\n$$H_0: \\mu_{\\text{test}} - \\mu_{\\text{ref}} \\leq -\\Delta_{NI}$$\n$$H_1: \\mu_{\\text{test}} - \\mu_{\\text{ref}} > -\\Delta_{NI}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Non-inferiority: new formulation vs. reference\n# NI margin = -5 mmHg; expected true difference = 0; SD = 12\ndelta_ni  <- 0     # true difference (expected: no difference)\nmargin_ni <- 5     # NI margin (mmHg)\nsigma_ni  <- 12\nalpha_ni  <- 0.025  # one-sided alpha\npower_ni  <- 0.90\n\n# For NI test: n = 2σ²(z_α + z_β)² / (margin - delta)²\nz_a <- qnorm(1 - alpha_ni)\nz_b <- qnorm(power_ni)\nn_ni <- ceiling(2 * sigma_ni^2 * (z_a + z_b)^2 / (margin_ni - delta_ni)^2)\n\ncat(\"=== Non-Inferiority Trial ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> === Non-Inferiority Trial ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"NI margin (Δ):         \", margin_ni, \"mmHg\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> NI margin (Δ):          5 mmHg\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Expected difference:   \", delta_ni, \"mmHg (no difference)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Expected difference:    0 mmHg (no difference)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"σ:                     \", sigma_ni, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> σ:                      12\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"α (one-sided):         \", alpha_ni, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> α (one-sided):          0.025\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Power (1-β):           \", power_ni, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Power (1-β):            0.9\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"n per arm:             \", n_ni, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> n per arm:              122\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total N:               \", n_ni * 2, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Total N:                244\n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare with superiority design\nn_sup <- ceiling(pwr.t.test(\n  d         = 5 / 12,\n  sig.level = 0.05,\n  power     = 0.90,\n  type      = \"two.sample\"\n)$n)\n\ncat(\"Equivalent superiority design (δ = 5 mmHg):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Equivalent superiority design (δ = 5 mmHg):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  n per arm:\", n_sup, \"| Total:\", n_sup * 2, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   n per arm: 123 | Total: 246\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"  (NI trials often need fewer patients since margin > 0)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>   (NI trials often need fewer patients since margin > 0)\n```\n\n\n:::\n:::\n\n\n### 5.2 Two One-Sided Tests (TOST) for Equivalence\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Bioequivalence: 80-125% rule (on log scale)\n# For log-transformed PK parameters: log(1.25) ≈ 0.223\nmargin_be <- log(1.25)\nsigma_be  <- 0.25      # CV ≈ 25% for PK data\npower_be  <- 0.90\nalpha_be  <- 0.05\n\nn_be <- ceiling(\n  2 * sigma_be^2 * (qnorm(1 - alpha_be) + qnorm(power_be))^2 / margin_be^2\n)\n\ncat(\"=== Bioequivalence (TOST) ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> === Bioequivalence (TOST) ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"BE margin:    ±\", round(margin_be, 4), \"(log scale) = 80–125% ratio\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> BE margin:    ± 0.2231 (log scale) = 80–125% ratio\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"CV (σ):       \", sigma_be, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> CV (σ):        0.25\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Power:        \", power_be, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Power:         0.9\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sequences×periods (crossover): 2 × 2\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Sequences×periods (crossover): 2 × 2\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"n subjects:   \", n_be, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> n subjects:    22\n```\n\n\n:::\n:::\n\n\n---\n\n## 6. Adjusting for Dropout and Protocol Deviations\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Account for expected dropout\nn_per_arm_base <- n_sbp    # from earlier calculation\ndropout_rate   <- 0.15     # 15% dropout expected\n\nn_inflated <- ceiling(n_per_arm_base / (1 - dropout_rate))\n\ncat(\"=== Inflating for Dropout ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> === Inflating for Dropout ===\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Required completers per arm: \", n_per_arm_base, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Required completers per arm:  191\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Expected dropout rate:       \", dropout_rate * 100, \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Expected dropout rate:        15 %\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Required enrolled per arm:   \", n_inflated, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Required enrolled per arm:    225\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total to enrol:              \", n_inflated * 2, \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> Total to enrol:               450\n```\n\n\n:::\n\n```{.r .cell-code}\n# Sensitivity: vary dropout\ntibble(\n  Dropout_rate  = seq(0.05, 0.30, by = 0.05),\n  n_to_enrol    = ceiling(n_per_arm_base / (1 - seq(0.05, 0.30, by = 0.05))),\n  Total_enrol   = 2 * ceiling(n_per_arm_base / (1 - seq(0.05, 0.30, by = 0.05)))\n) |>\n  mutate(Dropout_rate = paste0(Dropout_rate * 100, \"%\")) |>\n  gt() |>\n  tab_header(title = \"Sample Size Inflation for Dropout\",\n             subtitle = paste0(\"Base n = \", n_per_arm_base, \" completers per arm\"))\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Sample Size Inflation for Dropout\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  Base n = 191 completers per arm\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}rrr}\n\\toprule\nDropout\\_rate & n\\_to\\_enrol & Total\\_enrol \\\\ \n\\midrule\\addlinespace[2.5pt]\n5\\% & 202 & 404 \\\\ \n10\\% & 213 & 426 \\\\ \n15\\% & 225 & 450 \\\\ \n20\\% & 239 & 478 \\\\ \n25\\% & 255 & 510 \\\\ \n30\\% & 273 & 546 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n---\n\n## 7. Adaptive and Group Sequential Designs\n\n### 7.1 Group Sequential Designs\n\nGroup sequential designs allow pre-planned interim analyses with the option to stop early for efficacy or futility, while controlling the overall Type I error rate.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# O'Brien-Fleming boundaries for 2 interim + final analysis\n# Using simple z-score boundaries (illustrative)\nn_analyses   <- 3     # 2 interim + 1 final\nalpha_total  <- 0.05\n\n# Pocock spending function (constant boundaries)\nz_pocock <- qnorm(1 - alpha_total / (2 * n_analyses))\n\n# O'Brien-Fleming spending (conservative at interim, liberal at final)\ninfo_times <- c(1/3, 2/3, 1)   # information fraction at each analysis\nof_bounds <- qnorm(1 - alpha_total / 2) / sqrt(info_times)\n\ncat(\"=== Group Sequential Boundaries (Illustrative) ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> === Group Sequential Boundaries (Illustrative) ===\n```\n\n\n:::\n\n```{.r .cell-code}\ntibble(\n  Analysis       = c(\"Interim 1\", \"Interim 2\", \"Final\"),\n  Info_fraction  = info_times,\n  n_analysed     = ceiling(info_times * n_sbp * 2),\n  Pocock_z       = round(rep(z_pocock, 3), 3),\n  OBF_z          = round(of_bounds, 3),\n  Pocock_p       = round(2 * pnorm(-z_pocock), 4),\n  OBF_p          = round(2 * pnorm(-of_bounds), 4)\n) |>\n  gt() |>\n  tab_header(\n    title    = \"Group Sequential Efficacy Boundaries\",\n    subtitle = \"3-analysis design, α = 0.05 (two-sided)\"\n  ) |>\n  cols_label(\n    Info_fraction = \"Information Fraction\",\n    n_analysed    = \"N at Analysis\",\n    Pocock_z      = \"Pocock z\",\n    OBF_z         = \"O'Brien-Fleming z\",\n    Pocock_p      = \"Pocock p\",\n    OBF_p         = \"OBF p\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Group Sequential Efficacy Boundaries\\fontsize{12}{15}\\selectfont } \\\\ \n{\\fontsize{14}{17}\\selectfont  3-analysis design, α = 0.05 (two-sided)\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lrrrrrr}\n\\toprule\nAnalysis & Information Fraction & N at Analysis & Pocock z & O'Brien-Fleming z & Pocock p & OBF p \\\\ \n\\midrule\\addlinespace[2.5pt]\nInterim 1 & 0.3333333 & 128 & 2.394 & 3.395 & 0.0167 & 0.0007 \\\\ \nInterim 2 & 0.6666667 & 255 & 2.394 & 2.400 & 0.0167 & 0.0164 \\\\ \nFinal & 1.0000000 & 382 & 2.394 & 1.960 & 0.0167 & 0.0500 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n---\n\n## 8. Comprehensive Sample Size Summary Table\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntibble(\n  Design      = c(\n    \"Two-sample t-test (SBP, 90% power)\",\n    \"Two proportions (response, 80% power)\",\n    \"Log-rank survival (HR=0.70, 80% power)\",\n    \"Non-inferiority (continuous)\",\n    \"Bioequivalence (TOST crossover)\"\n  ),\n  Endpoint    = c(\"SBP change (mmHg)\", \"Response (Y/N)\",\n                  \"Overall survival\", \"BP endpoint (NI)\",\n                  \"AUC/Cmax ratio\"),\n  Key_assumption = c(\n    paste0(\"δ=5mmHg, σ=15, α=0.05\"),\n    paste0(\"p1=55%, p2=40%, α=0.05\"),\n    paste0(\"HR=0.70, α=0.05\"),\n    paste0(\"Margin=5mmHg, σ=12\"),\n    paste0(\"CV=25%, 80-125% rule\")\n  ),\n  n_per_arm   = c(n_sbp, n_bin, ceiling(n_subjects / 2), n_ni, n_be),\n  Total_N     = c(n_sbp * 2, n_bin * 2, n_subjects, n_ni * 2, n_be)\n) |>\n  gt() |>\n  tab_header(title = \"Summary: Sample Size Requirements Across Designs\") |>\n  cols_label(\n    Key_assumption = \"Key Assumptions\",\n    n_per_arm      = \"n per arm\",\n    Total_N        = \"Total N\"\n  )\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\caption*{\n{\\fontsize{20}{25}\\selectfont  Summary: Sample Size Requirements Across Designs\\fontsize{12}{15}\\selectfont }\n} \n\\fontsize{12.0pt}{14.0pt}\\selectfont\n\\begin{tabular*}{\\linewidth}{@{\\extracolsep{\\fill}}lllrr}\n\\toprule\nDesign & Endpoint & Key Assumptions & n per arm & Total N \\\\ \n\\midrule\\addlinespace[2.5pt]\nTwo-sample t-test (SBP, 90\\% power) & SBP change (mmHg) & δ=5mmHg, σ=15, α=0.05 & 191 & 382 \\\\ \nTwo proportions (response, 80\\% power) & Response (Y/N) & p1=55\\%, p2=40\\%, α=0.05 & 173 & 346 \\\\ \nLog-rank survival (HR=0.70, 80\\% power) & Overall survival & HR=0.70, α=0.05 & 246 & 492 \\\\ \nNon-inferiority (continuous) & BP endpoint (NI) & Margin=5mmHg, σ=12 & 122 & 244 \\\\ \nBioequivalence (TOST crossover) & AUC/Cmax ratio & CV=25\\%, 80-125\\% rule & 22 & 22 \\\\ \n\\bottomrule\n\\end{tabular*}\n\\end{table}\n\n:::\n:::\n\n\n---\n\n## Summary\n\nRigorous sample size calculation is a regulatory requirement and a scientific obligation. Key principles:\n\n- **Four parameters** — $\\alpha$, power, effect size, and $n$ — are interdependent: specify three, solve for the fourth\n- **The effect size is the most consequential input**: use the MCID, not an optimistic estimate, and conduct sensitivity analyses\n- **Standard designs**: two-sample t-test for continuous endpoints; two-proportion z-test for binary; log-rank for survival\n- **Event-driven survival trials**: power depends on the number of events, not just the sample size; recruitment and follow-up periods determine when events accumulate\n- **Non-inferiority and equivalence trials** use one-sided tests and require a pre-specified, scientifically justified NI margin\n- **Inflate for dropout**: always account for expected withdrawal when calculating the number to enrol\n- **Group sequential designs** allow for early stopping while maintaining overall error control\n- **Pre-registration**: sample size justification must be documented in the protocol and SAP before data collection begins\n\n> **Regulatory note**: ICH E9 requires that the sample size justification be included in the protocol, with explicit statements of the primary endpoint, assumed treatment difference, SD (or event rate), $\\alpha$, and power. Sensitivity analyses exploring the impact of varying assumptions are strongly recommended.\n",
    "supporting": [
      "bs07-sample-size-power_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"ss-continuous\",\"ss-continuous\",\"ss-continuous\",\"ss-continuous\",\"ss-continuous\",\"ss-continuous\",\"ss-continuous\",\"ss-binary\",\"ss-binary\",\"ss-binary\",\"ss-binary\",\"ss-binary\",\"ss-binary\",\"ss-binary\",\"ss-survival\",\"ss-survival\",\"ss-survival\",\"ss-survival\",\"ss-survival\",\"ss-survival\",\"ss-survival\",\"dropout-adjustment\",\"dropout-adjustment\",\"dropout-adjustment\",\"dropout-adjustment\",\"dropout-adjustment\",\"dropout-adjustment\",\"dropout-adjustment\",\"group-sequential\",\"group-sequential\",\"group-sequential\",\"group-sequential\",\"group-sequential\",\"group-sequential\",\"group-sequential\",\"ss-summary-table\",\"ss-summary-table\",\"ss-summary-table\",\"ss-summary-table\",\"ss-summary-table\",\"ss-summary-table\",\"ss-summary-table\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"caption\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"anyfontsize\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}